// packages/vue/src/components/glassmorphic/GlassTabs.vue
<script setup lang="ts">
/**
 * GlassTabs - Premium glassmorphic tabs component for Vue 3
 * 
 * Features:
 * - Animated tab indicator
 * - Multiple variants
 * - Icon support
 * - Lazy loading option
 * - Keyboard navigation
 */

import { ref, computed, watch, onMounted, nextTick } from 'vue';
import { cn } from '@archui/core';

interface Tab {
  id: string;
  label: string;
  icon?: string;
  disabled?: boolean;
}

interface GlassTabsProps {
  /** Tab items */
  tabs: Tab[];
  /** Active tab id */
  modelValue?: string;
  /** Visual variant */
  variant?: 'default' | 'pills' | 'underline' | 'glass' | 'bordered';
  /** Full width tabs */
  fullWidth?: boolean;
  /** Additional CSS classes */
  class?: string;
}

const props = withDefaults(defineProps<GlassTabsProps>(), {
  variant: 'default',
  fullWidth: false,
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void;
  (e: 'change', tab: Tab): void;
}>();

// Refs
const tabsRef = ref<HTMLDivElement | null>(null);
const indicatorStyle = ref({ left: '0px', width: '0px' });

// Active tab
const activeTab = computed({
  get: () => props.modelValue || props.tabs[0]?.id,
  set: (value: string) => {
    emit('update:modelValue', value);
    const tab = props.tabs.find(t => t.id === value);
    if (tab) emit('change', tab);
  },
});

// Select tab
const selectTab = (tab: Tab) => {
  if (tab.disabled) return;
  activeTab.value = tab.id;
};

// Update indicator position
const updateIndicator = () => {
  nextTick(() => {
    if (!tabsRef.value) return;
    const activeButton = tabsRef.value.querySelector(`[data-tab-id="${activeTab.value}"]`) as HTMLElement;
    if (activeButton) {
      indicatorStyle.value = {
        left: `${activeButton.offsetLeft}px`,
        width: `${activeButton.offsetWidth}px`,
      };
    }
  });
};

// Watch active tab changes
watch(activeTab, updateIndicator);

// Keyboard navigation
const handleKeydown = (e: KeyboardEvent) => {
  const enabledTabs = props.tabs.filter(t => !t.disabled);
  let newIndex = enabledTabs.findIndex(t => t.id === activeTab.value);
  
  switch (e.key) {
    case 'ArrowLeft':
      e.preventDefault();
      newIndex = newIndex > 0 ? newIndex - 1 : enabledTabs.length - 1;
      selectTab(enabledTabs[newIndex]);
      nextTick(() => {
        const newButton = tabsRef.value?.querySelector(`[data-tab-id="${enabledTabs[newIndex].id}"]`) as HTMLElement;
        newButton?.focus();
      });
      break;
    case 'ArrowRight':
      e.preventDefault();
      newIndex = newIndex < enabledTabs.length - 1 ? newIndex + 1 : 0;
      selectTab(enabledTabs[newIndex]);
      nextTick(() => {
        const newButton = tabsRef.value?.querySelector(`[data-tab-id="${enabledTabs[newIndex].id}"]`) as HTMLElement;
        newButton?.focus();
      });
      break;
  }
};

// Tab button classes
const getTabClasses = (tab: Tab) => {
  const isActive = tab.id === activeTab.value;
  
  const variants = {
    default: cn(
      'relative z-10',
      'px-4 py-2',
      'text-sm font-medium',
      'transition-colors duration-200',
      // Fix layout shift
      'before:block before:content-[attr(data-text)] before:font-bold before:h-0 before:invisible before:overflow-hidden',
      tab.disabled
        ? 'opacity-50 cursor-not-allowed'
        : isActive
          ? 'text-slate-900 dark:text-white'
          : 'text-slate-600 dark:text-white/60 hover:text-slate-900 dark:hover:text-white/80'
    ),
    pills: cn(
      'px-4 py-2',
      'rounded-lg',
      'text-sm font-medium',
      'transition-all duration-200',
      tab.disabled
        ? 'opacity-50 cursor-not-allowed'
        : isActive
          ? 'bg-slate-900 text-white shadow-md dark:bg-white dark:text-slate-900'
          : 'text-slate-700 dark:text-white/60 hover:bg-slate-200 dark:hover:bg-white/10'
    ),
    underline: cn(
      'relative',
      'px-4 py-3',
      'text-sm font-medium',
      'transition-colors duration-200',
      tab.disabled
        ? 'opacity-50 cursor-not-allowed'
        : isActive
          ? 'text-slate-900 dark:text-white'
          : 'text-slate-600 dark:text-white/60 hover:text-slate-900 dark:hover:text-white/80'
    ),
    glass: cn(
      'relative z-10',
      'px-4 py-2',
      'text-sm font-medium',
      'transition-colors duration-200',
      // Fix layout shift
      'before:block before:content-[attr(data-text)] before:font-bold before:h-0 before:invisible before:overflow-hidden',
      tab.disabled
        ? 'opacity-50 cursor-not-allowed'
        : isActive
          ? 'text-slate-900 dark:text-white font-semibold'
          : 'text-slate-700 dark:text-white/70 hover:text-slate-900 dark:hover:text-white'
    ),
    bordered: cn(
      'relative z-10',
      'px-4 py-2',
      'text-sm font-medium',
      'transition-colors duration-200',
      // Fix layout shift
      'before:block before:content-[attr(data-text)] before:font-bold before:h-0 before:invisible before:overflow-hidden',
      tab.disabled
        ? 'opacity-50 cursor-not-allowed'
        : isActive
          ? 'bg-slate-100 text-slate-900 dark:bg-white/10 dark:text-white font-semibold rounded-lg'
          : 'text-slate-600 dark:text-white/60 hover:text-slate-900 hover:bg-slate-50 dark:hover:text-white dark:hover:bg-white/5 rounded-lg'
    ),
  };
  
  return variants[props.variant];
};

// Container classes
const containerClasses = computed(() => {
  const variants = {
    default: cn(
      'relative',
      'inline-flex',
      'p-1',
      'rounded-xl',
      'bg-slate-100', // Solid light gray
      'dark:bg-white/[0.06]',
      'backdrop-blur-sm',
      'border border-slate-200 dark:border-white/[0.08]'
    ),
    pills: cn(
      'inline-flex gap-1',
      'p-1',
      'rounded-xl',
      'bg-slate-100 dark:bg-transparent', // Solid light gray
      'border border-slate-200 dark:border-transparent'
    ),
    underline: cn(
      'inline-flex',
      'border-b-2 border-slate-200 dark:border-white/10'
    ),
    glass: cn(
      'relative',
      'inline-flex',
      'p-1.5',
      'rounded-xl',
      // Light theme - TINTED for visibility
      'bg-white/70 dark:bg-white/[0.06]',
      'backdrop-blur-md',
      'border border-white/40 dark:border-white/[0.1]',
      'shadow-[0_4px_12px_rgba(0,0,0,0.05),0_1px_0_rgba(255,255,255,0.6)_inset]'
    ),
    bordered: cn(
      'relative',
      'inline-flex',
      'p-1',
      'rounded-xl',
      'bg-white dark:bg-slate-900',
      'border-2 border-slate-200 dark:border-white/[0.15]',
      'shadow-sm'
    ),
  };
  return cn(variants[props.variant] || variants.default, props.fullWidth && 'w-full', props.class);
});

// Lifecycle
onMounted(() => {
  if (props.variant === 'default') {
    updateIndicator();
  }
});
</script>

<template>
  <div>
    <!-- Tab List -->
    <div
      ref="tabsRef"
      :class="containerClasses"
      role="tablist"
    >
      <!-- Animated indicator (for default variant) -->
      <div
        v-if="variant === 'default' || variant === 'glass' || variant === 'bordered'"
        class="absolute top-1 bottom-1 rounded-lg bg-white dark:bg-white/[0.15] shadow-md border border-slate-200/50 dark:border-white/[0.1] transition-all duration-200 ease-out"
        :style="indicatorStyle"
      />
      
      <!-- Tabs -->
      <button
        v-for="tab in tabs"
        :key="tab.id"
        type="button"
        role="tab"
        :data-tab-id="tab.id"
        :data-text="tab.label"
        :aria-selected="tab.id === activeTab"
        :aria-controls="`tabpanel-${tab.id}`"
        :tabindex="tab.id === activeTab ? 0 : -1"
        :disabled="tab.disabled"
        :class="[
          getTabClasses(tab),
          fullWidth && 'flex-1'
        ]"
        @click="selectTab(tab)"
        @keydown="handleKeydown($event)"
      >
        <span class="flex items-center gap-2">
          <slot :name="`icon-${tab.id}`" />
          {{ tab.label }}
        </span>
        
        <!-- Underline indicator -->
        <span
          v-if="variant === 'underline' && tab.id === activeTab"
          class="absolute bottom-0 left-0 right-0 h-0.5 bg-slate-900 dark:bg-white"
        />
      </button>
    </div>

    <!-- Tab Panels -->
    <div class="mt-4">
      <template v-for="tab in tabs" :key="tab.id">
        <div
          v-show="tab.id === activeTab"
          :id="`tabpanel-${tab.id}`"
          role="tabpanel"
          :aria-labelledby="tab.id"
        >
          <slot :name="tab.id" />
        </div>
      </template>
    </div>
  </div>
</template>

// packages/react/src/components/glassmorphic/glass-tabs/glass-tabs.tsx
'use client';

import * as React from 'react';
import { cva } from 'class-variance-authority';
import { cn } from '@archui/core';
import { motion, AnimatePresence } from 'motion/react';

// Tabs Root Context
interface TabsContextValue {
  value: string;
  onValueChange: (value: string) => void;
  variant: 'default' | 'pills' | 'underline' | 'glass' | 'bordered';
  size: 'sm' | 'md' | 'lg';
  orientation: 'horizontal' | 'vertical';
  id: string; // Accessibility: Shared ID for linking
}

const TabsContext = React.createContext<TabsContextValue | null>(null);

function useTabsContext() {
  const context = React.useContext(TabsContext);
  if (!context) {
    throw new Error('Tab components must be used within a GlassTabs component');
  }
  return context;
}

// Tabs List Variants
const glassTabsListVariants = cva(
  [
    'flex',
    'transition-all duration-200',
  ],
  {
    variants: {
      variant: {
        default: [
          'bg-interactive-bg',
          'p-1 rounded-xl gap-1 backdrop-blur-sm',
        ],
        pills: [
          'gap-2',
        ],
        underline: [
          'gap-1',
          'border-b border-surface-border',
        ],
        glass: [
          'bg-white/40 backdrop-blur-xl',
          'border border-white/40',
          'dark:bg-white/[0.05] dark:border-white/10',
          'p-1 rounded-xl gap-1',
          'shadow-[0_4px_20px_-4px_rgba(0,0,0,0.05)]',
        ],
        bordered: [
          'border border-surface-border-strong',
          'p-1 rounded-lg gap-1',
        ],
      },
      orientation: {
        horizontal: 'flex-row items-center',
        vertical: 'flex-col items-stretch',
      },
      size: {
        sm: '',
        md: '',
        lg: '',
      },
    },
    defaultVariants: {
      variant: 'default',
      orientation: 'horizontal',
      size: 'md',
    },
  }
);

// Tab Trigger Variants
const glassTabsTriggerVariants = cva(
  [
    'relative inline-flex items-center justify-center gap-2',
    'font-medium whitespace-nowrap',
    'transition-colors duration-200',
    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2',
    'disabled:pointer-events-none disabled:opacity-50',
  ],
  {
    variants: {
      variant: {
        default: [
          'rounded-lg',
          'text-text-secondary',
          'hover:text-text-primary',
          'data-[state=active]:text-text-primary',
        ],
        pills: [
          'rounded-full',
          'text-text-secondary',
          'hover:bg-interactive-bg-hover',
          'hover:text-text-primary',
          'data-[state=active]:text-white dark:data-[state=active]:text-slate-900',
        ],
        underline: [
          'rounded-sm pb-3 -mb-px',
          'text-text-secondary',
          'hover:text-text-primary',
          'data-[state=active]:text-text-primary',
        ],
        glass: [
          'rounded-lg',
          'text-text-secondary',
          'hover:bg-interactive-bg-hover',
          'data-[state=active]:text-text-primary',
        ],
        bordered: [
          'rounded-md',
          'text-text-secondary',
          'hover:text-text-primary',
          'hover:bg-interactive-bg',
          'data-[state=active]:text-text-primary',
        ],
      },
      size: {
        sm: 'px-3 py-1.5 text-xs',
        md: 'px-4 py-2 text-sm',
        lg: 'px-6 py-2.5 text-base',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'md',
    },
  }
);

// Tabs Root Component
export interface GlassTabsProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onChange'> {
  value?: string;
  defaultValue?: string;
  onValueChange?: (value: string) => void;
  variant?: 'default' | 'pills' | 'underline' | 'glass' | 'bordered';
  size?: 'sm' | 'md' | 'lg';
  orientation?: 'horizontal' | 'vertical';
}

const GlassTabs = React.forwardRef<HTMLDivElement, GlassTabsProps>(
  ({
    children,
    className,
    value: controlledValue,
    defaultValue,
    onValueChange,
    variant = 'default',
    size = 'md',
    orientation = 'horizontal',
    ...props
  }, ref) => {
    const [uncontrolledValue, setUncontrolledValue] = React.useState(defaultValue || '');
    const isControlled = controlledValue !== undefined;
    const value = isControlled ? controlledValue : uncontrolledValue;

    const handleValueChange = React.useCallback((newValue: string) => {
      if (!isControlled) {
        setUncontrolledValue(newValue);
      }
      onValueChange?.(newValue);
    }, [isControlled, onValueChange]);

    const id = React.useId();

    return (
      <TabsContext.Provider value={{ value, onValueChange: handleValueChange, variant, size, orientation, id }}>
        <div
          ref={ref}
          className={cn(
            'flex',
            orientation === 'horizontal' ? 'flex-col' : 'flex-row gap-4',
            className
          )}
          {...props}
        >
          {children}
        </div>
      </TabsContext.Provider>
    );
  }
);

GlassTabs.displayName = 'GlassTabs';

// Tabs List Component
export interface GlassTabsListProps extends React.HTMLAttributes<HTMLDivElement> { }

const GlassTabsList = React.forwardRef<HTMLDivElement, GlassTabsListProps>(
  ({ className, children, ...props }, ref) => {
    const { variant, size, orientation, value, onValueChange } = useTabsContext();
    const listRef = React.useRef<HTMLDivElement>(null);

    // Handle Keyboard Navigation (Roving TabIndex)
    const handleKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => {
      const list = listRef.current;
      if (!list) return;

      const triggers = Array.from(list.querySelectorAll('[role="tab"]:not([disabled])')) as HTMLElement[];
      const index = triggers.findIndex((trigger) => trigger.getAttribute('data-value') === value);

      let nextIndex = index;

      switch (event.key) {
        case 'ArrowRight':
        case 'ArrowDown':
          nextIndex = index + 1;
          if (nextIndex >= triggers.length) nextIndex = 0;
          break;
        case 'ArrowLeft':
        case 'ArrowUp':
          nextIndex = index - 1;
          if (nextIndex < 0) nextIndex = triggers.length - 1;
          break;
        case 'Home':
          nextIndex = 0;
          break;
        case 'End':
          nextIndex = triggers.length - 1;
          break;
        default:
          return;
      }

      event.preventDefault();
      const nextTrigger = triggers[nextIndex];
      if (nextTrigger) {
        nextTrigger.focus();
        // Setup automatic activation or manual? Standard is manual for tabs, but accessible pattern often activates on focus for simple tabs.
        // Let's stick to manual activation (enter/space) OR click, but focus moves. 
        // Actually WAI-ARIA best practice:
        // - "Selection follows focus" is optional.
        // Let's implement "Selection follows focus" for smoother UX as most modern tabs do.
        const nextValue = nextTrigger.getAttribute('data-value');
        if (nextValue) onValueChange(nextValue);
      }
    };

    return (
      <div
        ref={(node) => {
          // Maintain both refs
          if (typeof ref === 'function') ref(node);
          else if (ref) (ref as React.MutableRefObject<HTMLDivElement | null>).current = node;
          (listRef as React.MutableRefObject<HTMLDivElement | null>).current = node;
        }}
        role="tablist"
        aria-orientation={orientation}
        onKeyDown={handleKeyDown}
        className={cn(
          glassTabsListVariants({ variant, size, orientation }),
          className
        )}
        {...props}
      >
        {children}
      </div>
    );
  }
);

GlassTabsList.displayName = 'GlassTabsList';

// Tab Trigger Component
export interface GlassTabsTriggerProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  value: string;
  icon?: React.ReactNode;
  badge?: React.ReactNode;
}

const GlassTabsTrigger = React.forwardRef<HTMLButtonElement, GlassTabsTriggerProps>(
  ({ className, value, children, icon, badge, disabled, ...props }, ref) => {
    const { value: selectedValue, onValueChange, variant, size, id } = useTabsContext();
    const isActive = selectedValue === value;
    const triggerId = `${id}-trigger-${value}`;
    const contentId = `${id}-content-${value}`;
    const getActiveIndicatorClasses = () => {
      switch (variant) {
        case 'default': return 'bg-surface-bg shadow-sm rounded-lg inset-0';
        case 'pills': return 'bg-slate-900 dark:bg-white shadow-sm rounded-full inset-0';
        case 'underline': return 'h-0.5 bg-slate-900 dark:bg-white bottom-0 left-0 right-0';
        case 'glass': return 'bg-surface-bg shadow-md rounded-lg inset-0';
        case 'bordered': return 'bg-surface-bg border border-surface-border-strong rounded-md inset-0';
        default: return 'inset-0';
      }
    };

    return (
      <button
        ref={ref}
        id={triggerId}
        role="tab"
        type="button"
        aria-selected={isActive}
        aria-controls={contentId}
        data-state={isActive ? 'active' : 'inactive'}
        data-value={value}
        tabIndex={isActive ? 0 : -1} // Roving TabIndex
        disabled={disabled}
        onClick={() => onValueChange(value)}
        className={cn(
          glassTabsTriggerVariants({ variant, size }),
          // Fix layout shift on bold hover/active
          "before:block before:content-[attr(data-text)] before:font-bold before:h-0 before:invisible before:overflow-hidden",
          className
        )}
        data-text={typeof children === 'string' ? children : undefined}
        {...props}
      >
        {isActive && (
          <motion.div
            layoutId={`${id}-active-tab-indicator`}
            className={cn("absolute pointer-events-none z-0", getActiveIndicatorClasses())}
            transition={{ type: "spring", stiffness: 400, damping: 30 }}
            initial={false}
          />
        )}
        {icon && <span className="flex-shrink-0 relative z-10">{icon}</span>}
        <span className="relative z-10 truncate">{children}</span>
        {badge && <span className="flex-shrink-0 relative z-10">{badge}</span>}
      </button>
    );
  }
);

GlassTabsTrigger.displayName = 'GlassTabsTrigger';

// Tab Content Component
export interface GlassTabsContentProps extends React.HTMLAttributes<HTMLDivElement> {
  value: string;
  forceMount?: boolean;
}

const GlassTabsContent = React.forwardRef<HTMLDivElement, GlassTabsContentProps>(
  ({ className, value, children, forceMount, ...props }, ref) => {
    const { value: selectedValue, orientation, id } = useTabsContext();
    const isActive = selectedValue === value;
    const triggerId = `${id}-trigger-${value}`;
    const contentId = `${id}-content-${value}`;

    if (!forceMount && !isActive) {
      return null;
    }

    return (
      <div
        ref={ref}
        id={contentId}
        role="tabpanel"
        aria-labelledby={triggerId}
        data-state={isActive ? 'active' : 'inactive'}
        hidden={!isActive}
        tabIndex={0}
        className={cn(
          'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2',
          orientation === 'horizontal' ? 'mt-3' : '',
          className
        )}
        {...props}
      >
        <AnimatePresence mode="wait">
          {isActive && (
            <motion.div
              key={value}
              initial={{ opacity: 0, y: 4, filter: 'blur(4px)' }}
              animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
              exit={{ opacity: 0, y: 4, filter: 'blur(4px)' }}
              transition={{ duration: 0.2, ease: "easeOut" }}
            >
              {children}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    );
  }
);

GlassTabsContent.displayName = 'GlassTabsContent';

export {
  GlassTabs,
  GlassTabsList,
  GlassTabsTrigger,
  GlassTabsContent,
  glassTabsListVariants,
  glassTabsTriggerVariants,
};
