// packages/vue/src/components/blocks/bento/BentoGrid.vue
<template>
  <section class="py-16 md:py-24 px-6" :class="className">
    <slot name="background" />

    <div v-if="heading || subheading" class="mx-auto max-w-3xl text-center mb-12">
      <h2 v-if="heading" class="text-3xl md:text-4xl font-bold tracking-tight text-[var(--glass-text)] dark:text-zinc-100 mb-4">
        {{ heading }}
      </h2>
      <p v-if="subheading" class="text-base md:text-lg text-[var(--glass-text)]/60 dark:text-zinc-400 leading-relaxed">
        {{ subheading }}
      </p>
    </div>

    <div
      ref="gridRef"
      :class="['grid auto-rows-fr gap-4 md:gap-5 mx-auto max-w-7xl', colsClass]"
    >
      <div
        v-for="(item, i) in items"
        :key="i"
        :style="{ transitionDelay: revealed ? `${i * 60}ms` : '0ms' }"
        :class="[
          'relative isolate overflow-hidden rounded-2xl',
          'border border-[var(--glass-edge,theme(colors.zinc.200))] dark:border-zinc-800',
          'bg-[var(--glass-surface,white)] dark:bg-zinc-900 backdrop-blur-md',
          'transition-all duration-500 ease-[cubic-bezier(0.4,0,0.2,1)]',
          revealed ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8',
          'hover:-translate-y-1.5 hover:shadow-[0_12px_40px_rgba(0,0,0,0.08)]',
          'dark:hover:shadow-[0_12px_40px_rgba(0,0,0,0.3)] dark:hover:border-zinc-700',
          item.colSpan === 2 ? 'md:col-span-2' : '',
          item.rowSpan === 2 ? 'md:row-span-2' : '',
          item.image ? 'min-h-[280px] flex flex-col justify-end' : 'p-6 md:p-8',
        ]"
        @mouseenter="hovered[i] = true"
        @mouseleave="hovered[i] = false"
      >
        <!-- Accent top edge -->
        <div
          v-if="item.accent"
          aria-hidden="true"
          class="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-[var(--glass-accent,theme(colors.amber.500))] to-transparent"
        />

        <!-- Shimmer sweep -->
        <div
          aria-hidden="true"
          :class="[
            'absolute inset-0 bg-gradient-to-br from-[var(--glass-accent)]/0 via-[var(--glass-accent)]/5 to-[var(--glass-accent)]/0',
            'transition-opacity duration-500',
            hovered[i] ? 'opacity-100' : 'opacity-0',
          ]"
        />

        <!-- Background image -->
        <template v-if="item.image">
          <img
            :src="item.image"
            alt=""
            aria-hidden="true"
            :class="[
              'absolute inset-0 h-full w-full object-cover',
              'transition-transform duration-500 ease-[cubic-bezier(0.4,0,0.2,1)]',
              hovered[i] ? 'scale-105' : 'scale-100',
            ]"
          />
          <div class="absolute inset-0 bg-gradient-to-t from-black/70 via-black/30 to-transparent" />
        </template>

        <!-- Content -->
        <div :class="['relative z-10', item.image ? 'p-6 md:p-8' : '']">
          <span
            v-if="item.tag"
            class="mb-3 inline-block rounded-full px-3 py-1 text-xs font-semibold bg-[var(--glass-accent)]/10 text-[var(--glass-accent,theme(colors.amber.600))] dark:text-amber-400"
          >{{ item.tag }}</span>

          <div
            v-if="item.icon"
            class="mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-[var(--glass-accent)]/10 text-[var(--glass-accent)] dark:text-amber-400"
          >
            <component :is="item.icon" v-if="typeof item.icon !== 'string'" />
            <span v-else v-html="item.icon" />
          </div>

          <h3
            :class="[
              'text-base md:text-lg font-semibold leading-snug mb-2',
              item.image ? 'text-white' : 'text-[var(--glass-text)] dark:text-zinc-100',
            ]"
          >{{ item.title }}</h3>

          <p
            v-if="item.body"
            :class="[
              'text-sm leading-relaxed',
              item.image ? 'text-white/75' : 'text-[var(--glass-text)]/70 dark:text-zinc-400',
            ]"
          >{{ item.body }}</p>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { ref, reactive, computed, onMounted, onUnmounted } from 'vue';

interface BentoItem {
  title: string;
  body?: string;
  icon?: unknown;
  tag?: string;
  colSpan?: 1 | 2;
  rowSpan?: 1 | 2;
  image?: string;
  accent?: boolean;
}

const props = withDefaults(defineProps<{
  heading?: string;
  subheading?: string;
  items: BentoItem[];
  columns?: 2 | 3 | 4;
  className?: string;
}>(), {
  columns: 3,
});

const revealed = ref(false);
const hovered = reactive<Record<number, boolean>>({});
const gridRef = ref<HTMLElement | null>(null);

let obs: IntersectionObserver | null = null;
onMounted(() => {
  if (!gridRef.value) return;
  obs = new IntersectionObserver(
    ([entry]) => { if (entry.isIntersecting) { revealed.value = true; obs?.disconnect(); } },
    { rootMargin: '0px 0px -60px 0px', threshold: 0.04 },
  );
  obs.observe(gridRef.value);
});
onUnmounted(() => obs?.disconnect());

const colsClass = computed(() => ({
  2: 'md:grid-cols-2',
  3: 'md:grid-cols-3',
  4: 'md:grid-cols-4',
}[props.columns]));
</script>

// packages/react/src/components/blocks/misc/bento-grid.tsx
'use client';

import * as React from 'react';
import { cn } from '@archui/core';

/* ------------------------------------------------------------------ */
/*  Types                                                               */
/* ------------------------------------------------------------------ */

export interface BentoGridItem {
  /** Card title */
  title: string;
  /** Card description */
  description?: string;
  /** Icon rendered in the card header */
  icon?: React.ReactNode;
  /** Optional cover image */
  image?: string;
  /** Grid span — defaults to { cols: 1, rows: 1 } */
  span?: { cols: 1 | 2; rows: 1 | 2 };
  /** Custom content to render inside the card */
  children?: React.ReactNode;
  /** Additional className for this cell */
  className?: string;
}

export interface BentoGridProps {
  /** Grid items */
  items: BentoGridItem[];
  /** Number of base columns */
  columns?: 2 | 3 | 4;
  /** Gap between cells */
  gap?: 'sm' | 'md' | 'lg';
  /** Additional className */
  className?: string;
}

/* ------------------------------------------------------------------ */
/*  Helpers                                                             */
/* ------------------------------------------------------------------ */

const colsMap = {
  2: 'md:grid-cols-2',
  3: 'md:grid-cols-3',
  4: 'md:grid-cols-4',
} as const;

const gapMap = { sm: 'gap-3', md: 'gap-5', lg: 'gap-8' } as const;

/* ------------------------------------------------------------------ */
/*  Component                                                           */
/* ------------------------------------------------------------------ */

export const BentoGrid = React.forwardRef<HTMLDivElement, BentoGridProps>(
  ({ items, columns = 3, gap = 'md', className }, ref) => {
    return (
      <div
        ref={ref}
        className={cn('grid auto-rows-[minmax(180px,1fr)] grid-cols-1', colsMap[columns], gapMap[gap], className)}
      >
        {items.map((item, i) => {
          const colSpan = item.span?.cols === 2 ? 'md:col-span-2' : '';
          const rowSpan = item.span?.rows === 2 ? 'md:row-span-2' : '';

          return (
            <div
              key={i}
              className={cn(
                'group relative flex flex-col overflow-hidden rounded-2xl',
                'border border-[var(--glass-edge)]',
                'bg-[var(--glass-surface)] backdrop-blur-md',
                'transition-all duration-300 hover:-translate-y-0.5 hover:shadow-lg',
                colSpan,
                rowSpan,
                item.className,
              )}
            >
              {/* Image */}
              {item.image && (
                <div className="relative flex-1 overflow-hidden">
                  <img
                    src={item.image}
                    alt={item.title}
                    className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
                    loading="lazy"
                  />
                  {/* Overlay for text readability */}
                  <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
                  <div className="absolute bottom-0 p-5">
                    {item.icon && (
                      <span className="mb-2 inline-block text-white/80 [&_svg]:h-5 [&_svg]:w-5">
                        {item.icon}
                      </span>
                    )}
                    <h3 className="text-sm font-semibold text-white">{item.title}</h3>
                    {item.description && (
                      <p className="mt-1 text-xs text-white/70 line-clamp-2">
                        {item.description}
                      </p>
                    )}
                  </div>
                </div>
              )}

              {/* No-image card */}
              {!item.image && (
                <div className="flex flex-1 flex-col p-6">
                  {item.icon && (
                    <span className="mb-3 text-[var(--glass-accent)] [&_svg]:h-6 [&_svg]:w-6">
                      {item.icon}
                    </span>
                  )}
                  <h3 className="text-sm font-semibold text-[var(--glass-text)]">{item.title}</h3>
                  {item.description && (
                    <p className="mt-2 text-xs text-[var(--glass-text)]/60 line-clamp-3">
                      {item.description}
                    </p>
                  )}
                  {item.children && <div className="mt-auto pt-4">{item.children}</div>}
                </div>
              )}
            </div>
          );
        })}
      </div>
    );
  },
);

BentoGrid.displayName = 'BentoGrid';
