// packages/vue/src/components/glassmorphic/GlassTooltip.vue
<script setup lang="ts">
/**
 * GlassTooltip - Token-based frosted glass tooltip for Vue 3
 */
import { ref, onUnmounted } from 'vue';
import { cn } from '@archui/core';

type GlassVariant = 'default' | 'solid' | 'bordered';

interface Props {
  content?: string;
  placement?: 'top' | 'bottom' | 'left' | 'right';
  delay?: number;
  variant?: GlassVariant;
  class?: string;
  disabled?: boolean;
}

const variantSurface: Record<GlassVariant, string> = {
  default: 'bg-[var(--glass-surface)] backdrop-blur-xl shadow-[var(--glass-depth-sm)]',
  solid: 'bg-[var(--glass-solid-bg)] backdrop-blur-2xl shadow-[var(--glass-solid-shadow)]',
  bordered: 'bg-[var(--glass-bordered-bg)] backdrop-blur-lg shadow-[var(--glass-bordered-shadow)]',
};
const variantBorder: Record<GlassVariant, string> = {
  default: 'border border-[var(--glass-edge)]',
  solid: 'border border-[var(--glass-solid-border)]',
  bordered: 'border border-[var(--glass-bordered-border)]',
};

const props = withDefaults(defineProps<Props>(), {
  content: '',
  placement: 'top',
  delay: 200,
  variant: 'default',
  disabled: false,
});

const visible = ref(false);
let showTimer: ReturnType<typeof setTimeout> | undefined;
let hideTimer: ReturnType<typeof setTimeout> | undefined;

const placementClasses: Record<string, string> = {
  top: 'bottom-full left-1/2 -translate-x-1/2 mb-2',
  bottom: 'top-full left-1/2 -translate-x-1/2 mt-2',
  left: 'right-full top-1/2 -translate-y-1/2 mr-2',
  right: 'left-full top-1/2 -translate-y-1/2 ml-2',
};

const arrowClasses: Record<string, string> = {
  top: 'top-full left-1/2 -translate-x-1/2 border-t-[var(--glass-surface)] border-l-transparent border-r-transparent border-b-transparent',
  bottom: 'bottom-full left-1/2 -translate-x-1/2 border-b-[var(--glass-surface)] border-l-transparent border-r-transparent border-t-transparent',
  left: 'left-full top-1/2 -translate-y-1/2 border-l-[var(--glass-surface)] border-t-transparent border-b-transparent border-r-transparent',
  right: 'right-full top-1/2 -translate-y-1/2 border-r-[var(--glass-surface)] border-t-transparent border-b-transparent border-l-transparent',
};

const show = () => {
  if (props.disabled) return;
  clearTimeout(hideTimer);
  showTimer = setTimeout(() => { visible.value = true; }, props.delay);
};

const hide = () => {
  clearTimeout(showTimer);
  visible.value = false;
};

onUnmounted(() => {
  clearTimeout(showTimer);
  clearTimeout(hideTimer);
});
</script>

<template>
  <div class="relative inline-flex" @mouseenter="show" @mouseleave="hide" @focus="show" @blur="hide">
    <slot />
    <Transition enter-active-class="transition-all duration-150" enter-from-class="opacity-0 scale-95"
      enter-to-class="opacity-100 scale-100" leave-active-class="transition-all duration-100"
      leave-from-class="opacity-100 scale-100" leave-to-class="opacity-0 scale-95">
      <div v-if="visible" :class="cn('absolute z-50 pointer-events-none', placementClasses[placement])" role="tooltip">
        <div :class="cn(
          'relative px-3 py-1.5 rounded-lg text-xs font-medium whitespace-nowrap',
          variantSurface[variant],
          variantBorder[variant],
          'text-[var(--glass-text)]',
          props.class,
        )">
          <slot name="content">{{ content }}</slot>
          <span :class="cn('absolute w-0 h-0 border-[5px]', arrowClasses[placement])" />
        </div>
      </div>
    </Transition>
  </div>
</template>

// packages/react/src/components/glassmorphic/glass-tooltip/glass-tooltip.tsx
'use client';

import * as React from 'react';
import { cn } from '@archui/core';
import {
    type GlassVariant,
    glassVariant,
    glassText,
    glassHighlight,
} from '../glass-interactive-variants';

/* ─── Types ─────────────────────────────────────────────── */

export type TooltipPlacement = 'top' | 'bottom' | 'left' | 'right';

export interface GlassTooltipProps {
    /** Tooltip content */
    content: React.ReactNode;
    /** Placement relative to trigger */
    placement?: TooltipPlacement;
    /** Delay before showing (ms) */
    delay?: number;
    /** Delay before hiding (ms) */
    hideDelay?: number;
    /** Visual variant */
    variant?: GlassVariant;
    /** Additional CSS classes for tooltip */
    className?: string;
    /** Trigger element */
    children: React.ReactElement;
    /** Disable tooltip */
    disabled?: boolean;
}

/* ─── Placement Utilities ───────────────────────────────── */

const placementStyles: Record<TooltipPlacement, string> = {
    top: 'bottom-full left-1/2 -translate-x-1/2 mb-2',
    bottom: 'top-full left-1/2 -translate-x-1/2 mt-2',
    left: 'right-full top-1/2 -translate-y-1/2 mr-2',
    right: 'left-full top-1/2 -translate-y-1/2 ml-2',
};

const enterAnimations: Record<TooltipPlacement, string> = {
    top: 'animate-in fade-in slide-in-from-bottom-1 zoom-in-95',
    bottom: 'animate-in fade-in slide-in-from-top-1 zoom-in-95',
    left: 'animate-in fade-in slide-in-from-right-1 zoom-in-95',
    right: 'animate-in fade-in slide-in-from-left-1 zoom-in-95',
};

const arrowSurfaceByVariant: Record<GlassVariant, Record<TooltipPlacement, string>> = {
    default: {
        top: 'top-full left-1/2 -translate-x-1/2 border-t-[var(--glass-surface)] border-l-transparent border-r-transparent border-b-transparent',
        bottom: 'bottom-full left-1/2 -translate-x-1/2 border-b-[var(--glass-surface)] border-l-transparent border-r-transparent border-t-transparent',
        left: 'left-full top-1/2 -translate-y-1/2 border-l-[var(--glass-surface)] border-t-transparent border-b-transparent border-r-transparent',
        right: 'right-full top-1/2 -translate-y-1/2 border-r-[var(--glass-surface)] border-t-transparent border-b-transparent border-l-transparent',
    },
    solid: {
        top: 'top-full left-1/2 -translate-x-1/2 border-t-[var(--glass-solid-bg)] border-l-transparent border-r-transparent border-b-transparent',
        bottom: 'bottom-full left-1/2 -translate-x-1/2 border-b-[var(--glass-solid-bg)] border-l-transparent border-r-transparent border-t-transparent',
        left: 'left-full top-1/2 -translate-y-1/2 border-l-[var(--glass-solid-bg)] border-t-transparent border-b-transparent border-r-transparent',
        right: 'right-full top-1/2 -translate-y-1/2 border-r-[var(--glass-solid-bg)] border-t-transparent border-b-transparent border-l-transparent',
    },
    bordered: {
        top: 'top-full left-1/2 -translate-x-1/2 border-t-[var(--glass-bordered-bg)] border-l-transparent border-r-transparent border-b-transparent',
        bottom: 'bottom-full left-1/2 -translate-x-1/2 border-b-[var(--glass-bordered-bg)] border-l-transparent border-r-transparent border-t-transparent',
        left: 'left-full top-1/2 -translate-y-1/2 border-l-[var(--glass-bordered-bg)] border-t-transparent border-b-transparent border-r-transparent',
        right: 'right-full top-1/2 -translate-y-1/2 border-r-[var(--glass-bordered-bg)] border-t-transparent border-b-transparent border-l-transparent',
    },
};

/* ─── Main Component ────────────────────────────────────── */

const GlassTooltip: React.FC<GlassTooltipProps> = ({
    content,
    placement = 'top',
    delay = 200,
    hideDelay = 0,
    variant = 'default',
    className,
    children,
    disabled = false,
}) => {
    const [visible, setVisible] = React.useState(false);
    const showTimerRef = React.useRef<ReturnType<typeof setTimeout>>();
    const hideTimerRef = React.useRef<ReturnType<typeof setTimeout>>();

    const v = glassVariant[variant];

    const show = React.useCallback(() => {
        if (disabled) return;
        clearTimeout(hideTimerRef.current);
        showTimerRef.current = setTimeout(() => setVisible(true), delay);
    }, [delay, disabled]);

    const hide = React.useCallback(() => {
        clearTimeout(showTimerRef.current);
        hideTimerRef.current = setTimeout(() => setVisible(false), hideDelay);
    }, [hideDelay]);

    React.useEffect(() => {
        return () => {
            clearTimeout(showTimerRef.current);
            clearTimeout(hideTimerRef.current);
        };
    }, []);

    return (
        <div className="relative inline-flex" onMouseEnter={show} onMouseLeave={hide} onFocus={show} onBlur={hide}>
            {children}
            {visible && (
                <div
                    className={cn(
                        'absolute z-50 pointer-events-none',
                        placementStyles[placement],
                        enterAnimations[placement],
                        'duration-150',
                    )}
                    style={{ animationTimingFunction: 'cubic-bezier(0.34, 1.56, 0.64, 1)' }}
                    role="tooltip"
                >
                    <div
                        className={cn(
                            'relative px-3 py-1.5 rounded-lg',
                            'text-xs font-medium whitespace-nowrap',
                            v.surface, v.border, glassHighlight,
                            glassText.primary,
                            className,
                        )}
                    >
                        {content}
                        <span className={cn('absolute w-0 h-0 border-[5px]', arrowSurfaceByVariant[variant][placement])} />
                    </div>
                </div>
            )}
        </div>
    );
};

GlassTooltip.displayName = 'GlassTooltip';

export { GlassTooltip };
