// packages/react/src/components/dashboard/ultra-minimal/MiniLineChart.tsx
'use client';

/**
 * MiniLineChart – Ultra-Minimal
 * Pure SVG line chart — no external chart library.
 * Renders a clean, Apple-style trend line.
 */

import * as React from 'react';
import type { ChartDataPoint } from '../shared/types';
import styles from './ultra-minimal.module.css';

interface MiniLineChartProps {
    data: ChartDataPoint[];
    title?: string;
}

export function MiniLineChart({ data, title = 'Revenue Trend' }: MiniLineChartProps) {
    const svgRef = React.useRef<SVGSVGElement>(null);

    // Build SVG path from data
    const viewBoxWidth = 600;
    const viewBoxHeight = 240;
    const paddingX = 40;
    const paddingY = 24;
    const chartWidth = viewBoxWidth - paddingX * 2;
    const chartHeight = viewBoxHeight - paddingY * 2;

    const maxValue = Math.max(...data.map((d) => d.value));
    const minValue = Math.min(...data.map((d) => d.value));
    const range = maxValue - minValue || 1;

    const points = data.map((d, i) => {
        const x = paddingX + (i / (data.length - 1)) * chartWidth;
        const y = paddingY + chartHeight - ((d.value - minValue) / range) * chartHeight;
        return { x, y, label: d.name, value: d.value };
    });

    const linePath = points.map((p, i) => `${i === 0 ? 'M' : 'L'} ${p.x} ${p.y}`).join(' ');

    // Filled area path
    const areaPath = `${linePath} L ${points[points.length - 1].x} ${paddingY + chartHeight} L ${points[0].x} ${paddingY + chartHeight} Z`;

    // Horizontal grid lines (4 lines)
    const gridLines = Array.from({ length: 5 }, (_, i) => {
        const y = paddingY + (i / 4) * chartHeight;
        const value = maxValue - (i / 4) * range;
        return { y, value: Math.round(value).toLocaleString() };
    });

    return (
        <div className={styles.chartCard}>
            <h3 className={styles.chartTitle}>{title}</h3>
            <div className={styles.chartWrapper}>
                <svg
                    ref={svgRef}
                    viewBox={`0 0 ${viewBoxWidth} ${viewBoxHeight}`}
                    preserveAspectRatio="none"
                    width="100%"
                    height="100%"
                    role="img"
                    aria-label={`${title} chart showing data over time`}
                >
                    {/* Grid lines */}
                    {gridLines.map((line) => (
                        <g key={line.value}>
                            <line
                                x1={paddingX}
                                y1={line.y}
                                x2={viewBoxWidth - paddingX}
                                y2={line.y}
                                stroke="var(--dash-chart-grid)"
                                strokeWidth="1"
                            />
                            <text
                                x={paddingX - 8}
                                y={line.y + 3}
                                textAnchor="end"
                                fill="var(--dash-text-muted)"
                                fontSize="9"
                                fontFamily="inherit"
                            >
                                {line.value}
                            </text>
                        </g>
                    ))}

                    {/* X-axis labels */}
                    {points.map((p, i) =>
                        i % 2 === 0 ? (
                            <text
                                key={p.label}
                                x={p.x}
                                y={viewBoxHeight - 4}
                                textAnchor="middle"
                                fill="var(--dash-text-muted)"
                                fontSize="9"
                                fontFamily="inherit"
                            >
                                {p.label}
                            </text>
                        ) : null,
                    )}

                    {/* Area fill */}
                    <path d={areaPath} fill="var(--dash-chart-fill)" />

                    {/* Line */}
                    <path
                        d={linePath}
                        fill="none"
                        stroke="var(--dash-chart-stroke)"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                    />

                    {/* Data points */}
                    {points.map((p) => (
                        <circle
                            key={p.label}
                            cx={p.x}
                            cy={p.y}
                            r="3"
                            fill="var(--dash-surface)"
                            stroke="var(--dash-chart-stroke)"
                            strokeWidth="2"
                        />
                    ))}
                </svg>
            </div>
        </div>
    );
}

// packages/vue/src/components/dashboard/ultra-minimal/MiniLineChart.vue
<script setup lang="ts">
/**
 * MiniLineChart – Ultra-Minimal (Vue 3)
 * Pure SVG line chart — no external chart library.
 * Clean Apple-style trend line rendered from data.
 */

import { computed } from 'vue'
import type { ChartDataPoint } from '../shared/types'

const props = withDefaults(defineProps<{
  data: ChartDataPoint[]
  title?: string
}>(), {
  title: 'Revenue Trend'
})

const viewBoxWidth = 600
const viewBoxHeight = 240
const paddingX = 40
const paddingY = 24
const chartWidth = viewBoxWidth - paddingX * 2
const chartHeight = viewBoxHeight - paddingY * 2

const maxValue = computed(() => Math.max(...props.data.map(d => d.value)))
const minValue = computed(() => Math.min(...props.data.map(d => d.value)))
const range = computed(() => maxValue.value - minValue.value || 1)

const points = computed(() =>
  props.data.map((d, i) => ({
    x: paddingX + (i / (props.data.length - 1)) * chartWidth,
    y: paddingY + chartHeight - ((d.value - minValue.value) / range.value) * chartHeight,
    label: d.name,
    value: d.value,
  }))
)

const linePath = computed(() =>
  points.value.map((p, i) => `${i === 0 ? 'M' : 'L'} ${p.x} ${p.y}`).join(' ')
)

const areaPath = computed(() =>
  `${linePath.value} L ${points.value[points.value.length - 1].x} ${paddingY + chartHeight} L ${points.value[0].x} ${paddingY + chartHeight} Z`
)

const gridLines = computed(() =>
  Array.from({ length: 5 }, (_, i) => ({
    y: paddingY + (i / 4) * chartHeight,
    value: Math.round(maxValue.value - (i / 4) * range.value).toLocaleString(),
  }))
)
</script>

<template>
  <div :class="$style.chartCard">
    <h3 :class="$style.chartTitle">{{ title }}</h3>
    <div :class="$style.chartWrapper">
      <svg
        :viewBox="`0 0 ${viewBoxWidth} ${viewBoxHeight}`"
        preserveAspectRatio="none"
        width="100%"
        height="100%"
        role="img"
        :aria-label="`${title} chart showing data over time`"
      >
        <!-- Grid lines -->
        <g v-for="line in gridLines" :key="line.value">
          <line
            :x1="paddingX"
            :y1="line.y"
            :x2="viewBoxWidth - paddingX"
            :y2="line.y"
            stroke="var(--dash-chart-grid)"
            stroke-width="1"
          />
          <text
            :x="paddingX - 8"
            :y="line.y + 3"
            text-anchor="end"
            fill="var(--dash-text-muted)"
            font-size="9"
            font-family="inherit"
          >
            {{ line.value }}
          </text>
        </g>

        <!-- X-axis labels -->
        <template v-for="(p, i) in points" :key="`label-${p.label}`">
          <text
            v-if="i % 2 === 0"
            :x="p.x"
            :y="viewBoxHeight - 4"
            text-anchor="middle"
            fill="var(--dash-text-muted)"
            font-size="9"
            font-family="inherit"
          >
            {{ p.label }}
          </text>
        </template>

        <!-- Area fill -->
        <path :d="areaPath" fill="var(--dash-chart-fill)" />

        <!-- Line -->
        <path
          :d="linePath"
          fill="none"
          stroke="var(--dash-chart-stroke)"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
        />

        <!-- Data points -->
        <circle
          v-for="p in points"
          :key="`dot-${p.label}`"
          :cx="p.x"
          :cy="p.y"
          r="3"
          fill="var(--dash-surface)"
          stroke="var(--dash-chart-stroke)"
          stroke-width="2"
        />
      </svg>
    </div>
  </div>
</template>

<style module>
.chartCard {
  padding: 28px;
  border-radius: 16px;
  background: var(--dash-surface);
  border: 1px solid var(--dash-border-subtle);
  transition: background var(--dash-transition-fast),
              border-color var(--dash-transition-fast);
}

.chartTitle {
  font-size: 16px;
  font-weight: 600;
  color: var(--dash-text);
  margin: 0 0 24px;
  letter-spacing: -0.01em;
}

.chartWrapper {
  width: 100%;
  height: 280px;
}
</style>
