// packages/vue/src/components/glassmorphic/GlassDropdown.vue
<script setup lang="ts">
/**
 * GlassDropdown - Premium glassmorphic dropdown for Vue 3
 * 
 * Features:
 * - Frosted glass backdrop blur
 * - Click or hover trigger
 * - Multiple positions
 * - Keyboard navigation
 * - Click outside to close
 */

import { ref, computed, onMounted, onUnmounted, nextTick } from 'vue';
import { cn } from '@archui/core';

interface DropdownItem {
  id: string;
  label: string;
  icon?: string;
  disabled?: boolean;
  divider?: boolean;
  onClick?: () => void;
}

interface GlassDropdownProps {
  /** Dropdown items */
  items?: DropdownItem[];
  /** Trigger mode */
  trigger?: 'click' | 'hover';
  /** Dropdown position */
  position?: 'bottom-start' | 'bottom-end' | 'top-start' | 'top-end';
  /** Disabled state */
  disabled?: boolean;
  /** Additional CSS classes */
  class?: string;
}

const props = withDefaults(defineProps<GlassDropdownProps>(), {
  items: () => [],
  trigger: 'click',
  position: 'bottom-start',
  disabled: false,
});

const emit = defineEmits<{
  (e: 'select', item: DropdownItem): void;
  (e: 'open'): void;
  (e: 'close'): void;
}>();

// Refs
const triggerRef = ref<HTMLDivElement | null>(null);
const dropdownRef = ref<HTMLDivElement | null>(null);
const isOpen = ref(false);
const focusedIndex = ref(-1);

// Toggle dropdown
const toggle = () => {
  if (props.disabled) return;
  isOpen.value = !isOpen.value;
  if (isOpen.value) {
    emit('open');
    nextTick(() => focusedIndex.value = 0);
  } else {
    emit('close');
  }
};

const open = () => {
  if (props.disabled || isOpen.value) return;
  isOpen.value = true;
  emit('open');
};

const close = () => {
  if (!isOpen.value) return;
  isOpen.value = false;
  focusedIndex.value = -1;
  emit('close');
};

// Handle item select
const selectItem = (item: DropdownItem) => {
  if (item.disabled || item.divider) return;
  emit('select', item);
  if (item.onClick) item.onClick();
  close();
};

// Keyboard navigation
const handleKeydown = (e: KeyboardEvent) => {
  if (!isOpen.value) return;
  
  const enabledItems = props.items.filter(i => !i.disabled && !i.divider);
  
  switch (e.key) {
    case 'ArrowDown':
      e.preventDefault();
      focusedIndex.value = (focusedIndex.value + 1) % enabledItems.length;
      break;
    case 'ArrowUp':
      e.preventDefault();
      focusedIndex.value = focusedIndex.value <= 0 ? enabledItems.length - 1 : focusedIndex.value - 1;
      break;
    case 'Enter':
    case ' ':
      e.preventDefault();
      if (focusedIndex.value >= 0) {
        selectItem(enabledItems[focusedIndex.value]);
      }
      break;
    case 'Escape':
      e.preventDefault();
      close();
      break;
  }
};

// Click outside handler
const handleClickOutside = (e: MouseEvent) => {
  if (!triggerRef.value?.contains(e.target as Node) && 
      !dropdownRef.value?.contains(e.target as Node)) {
    close();
  }
};

// Position classes
const positionClasses = computed(() => {
  const positions = {
    'bottom-start': 'top-full left-0 mt-2',
    'bottom-end': 'top-full right-0 mt-2',
    'top-start': 'bottom-full left-0 mb-2',
    'top-end': 'bottom-full right-0 mb-2',
  };
  return positions[props.position];
});

// Lifecycle
onMounted(() => {
  document.addEventListener('click', handleClickOutside);
  document.addEventListener('keydown', handleKeydown);
});

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside);
  document.removeEventListener('keydown', handleKeydown);
});
</script>

<template>
  <div class="relative inline-block" :class="props.class">
    <!-- Trigger -->
    <div
      ref="triggerRef"
      @click="trigger === 'click' && toggle()"
      @mouseenter="trigger === 'hover' && open()"
      @mouseleave="trigger === 'hover' && close()"
    >
      <slot name="trigger">
        <button
          type="button"
          :class="cn(
            'px-4 py-2 rounded-xl',
            'bg-slate-100 dark:bg-white/[0.1]',
            'border border-slate-200 dark:border-transparent',
            'hover:bg-slate-200 dark:hover:bg-white/[0.15]',
            'transition-colors duration-200',
            disabled && 'opacity-50 cursor-not-allowed'
          )"
        >
          Options
        </button>
      </slot>
    </div>

    <!-- Dropdown menu -->
    <Transition
      enter-active-class="transition-all duration-200 ease-out"
      enter-from-class="opacity-0 scale-95 translate-y-1"
      enter-to-class="opacity-100 scale-100 translate-y-0"
      leave-active-class="transition-all duration-150 ease-in"
      leave-from-class="opacity-100 scale-100 translate-y-0"
      leave-to-class="opacity-0 scale-95 translate-y-1"
    >
      <div
        v-if="isOpen"
        ref="dropdownRef"
        :class="cn(
          'absolute z-50',
          positionClasses,
          'min-w-[200px]',
          'p-1.5',
          'rounded-xl',
          'backdrop-blur-xl',
          // Light theme - visible background (TINTED)
          'bg-white/70',
          'dark:bg-slate-900/95',
          'border border-white/40 dark:border-white/[0.1]',
          'shadow-[0_8px_32px_rgba(0,0,0,0.12)]',
          'dark:shadow-2xl dark:shadow-black/30'
        )"
        @mouseenter="trigger === 'hover' && open()"
        @mouseleave="trigger === 'hover' && close()"
      >
        <template v-for="(item, index) in items" :key="item.id">
          <!-- Divider -->
          <div
            v-if="item.divider"
            class="my-1 h-px bg-black/10 dark:bg-white/10"
          />
          
          <!-- Item -->
          <button
            v-else
            type="button"
            :class="cn(
              'w-full',
              'flex items-center gap-3',
              'px-3 py-2',
              'rounded-lg',
              'text-left text-sm',
              'transition-colors duration-150',
              item.disabled
                ? 'opacity-50 cursor-not-allowed'
                : [
                    'hover:bg-slate-100 dark:hover:bg-white/[0.08]',
                    focusedIndex === index && 'bg-slate-100 dark:bg-white/[0.08]'
                  ],
              'text-slate-900 dark:text-white/90'
            )"
            :disabled="item.disabled"
            @click="selectItem(item)"
          >
            <slot :name="`icon-${item.id}`" />
            <span>{{ item.label }}</span>
          </button>
        </template>
        
        <!-- Custom content slot -->
        <slot />
      </div>
    </Transition>
  </div>
</template>

// packages/react/src/components/glassmorphic/glass-dropdown/glass-dropdown.tsx
'use client';

import * as React from 'react';
import { createPortal } from 'react-dom';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from '@archui/core';

/**
 * Glass Dropdown Menu Variants
 */
const glassDropdownVariants = cva(
  [
    'absolute',
    'z-50',
    'min-w-[180px]',
    'rounded-xl',
    'overflow-hidden',
    'backdrop-blur-xl',
    'border',
    // Premium Glass
    'bg-white/80',
    'border-white/40',
    'shadow-[0_10px_40px_-10px_rgba(0,0,0,0.1),0_0_0_1px_rgba(255,255,255,0.5)_inset]',
    // Dark mode
    'dark:bg-black/60',
    'dark:border-white/10',
    'dark:shadow-[0_10px_40px_rgba(0,0,0,0.4),0_0_0_1px_rgba(255,255,255,0.1)_inset]',
    'py-1',
    'transition-all',
    'duration-200',
    'ease-out',
  ],
  {
    variants: {
      align: {
        start: 'left-0',
        center: 'left-1/2 -translate-x-1/2',
        end: 'right-0',
      },
    },
    defaultVariants: {
      align: 'start',
    },
  }
);

/**
 * Glass Dropdown Item Variants
 */
const glassDropdownItemVariants = cva(
  [
    'flex',
    'items-center',
    'gap-3',
    'w-full',
    'px-4',
    'py-2.5',
    'text-sm',
    // Semantic tokens
    'text-text-secondary',
    'transition-all',
    'duration-150',
    'cursor-pointer',
    'outline-none',
  ],
  {
    variants: {
      variant: {
        default: [
          'hover:bg-black/[0.04]',
          'dark:hover:bg-white/10',
          'hover:text-slate-900',
          'dark:hover:text-white',
          'focus:bg-black/[0.04]',
          'dark:focus:bg-white/10',
          'focus:text-slate-900',
          'dark:focus:text-white',
        ],
        danger: [
          'text-red-600 dark:text-red-400/80',
          'hover:bg-red-50 dark:hover:bg-red-500/10',
          'hover:text-red-700 dark:hover:text-red-400',
          'focus:bg-red-50 dark:focus:bg-red-500/10',
        ],
      },
      disabled: {
        true: [
          'opacity-50',
          'cursor-not-allowed',
          'pointer-events-none',
        ],
        false: '',
      },
    },
    defaultVariants: {
      variant: 'default',
      disabled: false,
    },
  }
);

// Context for dropdown state
interface DropdownContextValue {
  open: boolean;
  setOpen: (open: boolean) => void;
  triggerRef: React.RefObject<HTMLButtonElement>;
}

const DropdownContext = React.createContext<DropdownContextValue | null>(null);

const useDropdown = () => {
  const context = React.useContext(DropdownContext);
  if (!context) {
    throw new Error('Dropdown components must be used within a GlassDropdown');
  }
  return context;
};

export interface GlassDropdownProps {
  children: React.ReactNode;
  /** Controlled open state */
  open?: boolean;
  /** Callback when open state changes */
  onOpenChange?: (open: boolean) => void;
  /** Default open state (uncontrolled) */
  defaultOpen?: boolean;
}

/**
 * GlassDropdown - Root component for dropdown menu
 */
function GlassDropdown({
  children,
  open: controlledOpen,
  onOpenChange,
  defaultOpen = false,
}: GlassDropdownProps) {
  const [uncontrolledOpen, setUncontrolledOpen] = React.useState(defaultOpen);
  const triggerRef = React.useRef<HTMLButtonElement>(null);

  const open = controlledOpen ?? uncontrolledOpen;
  const setOpen = React.useCallback(
    (value: boolean) => {
      setUncontrolledOpen(value);
      onOpenChange?.(value);
    },
    [onOpenChange]
  );

  // Close on outside click
  React.useEffect(() => {
    if (!open) return;

    const handleClick = (e: MouseEvent) => {
      if (triggerRef.current?.contains(e.target as Node)) return;
      setOpen(false);
    };

    document.addEventListener('click', handleClick);
    return () => document.removeEventListener('click', handleClick);
  }, [open, setOpen]);

  // Close on escape
  React.useEffect(() => {
    if (!open) return;

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setOpen(false);
    };

    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [open, setOpen]);

  return (
    <DropdownContext.Provider value={{ open, setOpen, triggerRef }}>
      <div className="relative inline-block">{children}</div>
    </DropdownContext.Provider>
  );
}

export interface GlassDropdownTriggerProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  asChild?: boolean;
}

/**
 * GlassDropdownTrigger - Button that toggles the dropdown
 */
const GlassDropdownTrigger = React.forwardRef<
  HTMLButtonElement,
  GlassDropdownTriggerProps
>(({ className, children, onClick, ...props }, ref) => {
  const { open, setOpen, triggerRef } = useDropdown();

  // Merge refs
  React.useImperativeHandle(ref, () => triggerRef.current!);

  const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {
    setOpen(!open);
    onClick?.(e);
  };

  return (
    <button
      ref={triggerRef}
      className={className}
      onClick={handleClick}
      aria-expanded={open}
      aria-haspopup="menu"
      {...props}
    >
      {children}
    </button>
  );
});

GlassDropdownTrigger.displayName = 'GlassDropdownTrigger';

export interface GlassDropdownContentProps
  extends React.HTMLAttributes<HTMLDivElement>,
  VariantProps<typeof glassDropdownVariants> {
  /** Portal to body */
  portal?: boolean;
  /** Offset from trigger */
  sideOffset?: number;
}

/**
 * GlassDropdownContent - The dropdown menu container
 */
const GlassDropdownContent = React.forwardRef<
  HTMLDivElement,
  GlassDropdownContentProps
>(
  (
    {
      className,
      align,
      portal = false,
      sideOffset = 8,
      children,
      style,
      ...props
    },
    ref
  ) => {
    const { open, triggerRef } = useDropdown();
    const [position, setPosition] = React.useState({ top: 0, left: 0 });
    const [mounted, setMounted] = React.useState(false);

    React.useEffect(() => {
      setMounted(true);
    }, []);

    // Calculate position for portal
    React.useEffect(() => {
      if (!open || !portal || !triggerRef.current) return;

      const rect = triggerRef.current.getBoundingClientRect();
      setPosition({
        top: rect.bottom + sideOffset + window.scrollY,
        left: rect.left + window.scrollX,
      });
    }, [open, portal, sideOffset, triggerRef]);

    if (!open) return null;

    const content = (
      <div
        ref={ref}
        className={cn(
          glassDropdownVariants({ align }),
          !portal && 'top-full mt-2',
          open
            ? 'opacity-100 translate-y-0'
            : 'opacity-0 -translate-y-2 pointer-events-none',
          className
        )}
        style={
          portal
            ? { position: 'absolute', top: position.top, left: position.left, ...style }
            : style
        }
        role="menu"
        {...props}
      >
        {children}
      </div>
    );

    if (portal && mounted) {
      return createPortal(content, document.body);
    }

    return content;
  }
);

GlassDropdownContent.displayName = 'GlassDropdownContent';

export interface GlassDropdownItemProps
  extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'disabled'>,
  VariantProps<typeof glassDropdownItemVariants> {
  /** Icon to display before text */
  icon?: React.ReactNode;
  /** Shortcut key hint */
  shortcut?: string;
  /** Whether the item is disabled */
  disabled?: boolean;
}

/**
 * GlassDropdownItem - Individual menu item
 */
const GlassDropdownItem = React.forwardRef<
  HTMLButtonElement,
  GlassDropdownItemProps
>(
  (
    { className, variant, disabled, icon, shortcut, children, onClick, ...props },
    ref
  ) => {
    const { setOpen } = useDropdown();

    const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {
      if (disabled) return;
      onClick?.(e);
      setOpen(false);
    };

    return (
      <button
        ref={ref}
        className={cn(glassDropdownItemVariants({ variant, disabled }), className)}
        role="menuitem"
        disabled={disabled || false}
        onClick={handleClick}
        {...props}
      >
        {icon && <span className="w-4 h-4 flex-shrink-0">{icon}</span>}
        <span className="flex-1 text-left">{children}</span>
        {shortcut && (
          <span className="text-xs text-[var(--glass-text-muted)] ml-auto font-mono">{shortcut}</span>
        )}
      </button>
    );
  }
);

GlassDropdownItem.displayName = 'GlassDropdownItem';

/**
 * GlassDropdownSeparator - Visual separator between items
 */
const GlassDropdownSeparator = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn('h-px my-1 bg-[var(--glass-divider)]', className)}
    role="separator"
    {...props}
  />
));

GlassDropdownSeparator.displayName = 'GlassDropdownSeparator';

/**
 * GlassDropdownLabel - Group label for menu items
 */
const GlassDropdownLabel = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, children, ...props }, ref) => (
  <div
    ref={ref}
    className={cn(
      'px-4 py-2 text-xs font-semibold text-[var(--glass-text-muted)] uppercase tracking-wider',
      className
    )}
    {...props}
  >
    {children}
  </div>
));

GlassDropdownLabel.displayName = 'GlassDropdownLabel';

export {
  GlassDropdown,
  GlassDropdownTrigger,
  GlassDropdownContent,
  GlassDropdownItem,
  GlassDropdownSeparator,
  GlassDropdownLabel,
  glassDropdownVariants,
  glassDropdownItemVariants,
};
