// packages/vue/src/components/glassmorphic/GlassColorSwatch.vue
<script setup lang="ts">
/**
 * GlassColorSwatch - Clickable color chip with clipboard copy
 */
import { ref, computed } from 'vue';
import { cn } from '@archui/core';

interface GlassColorSwatchProps {
  color: string;
  label?: string;
  selected?: boolean;
  size?: 'sm' | 'md' | 'lg';
  class?: string;
}

const props = withDefaults(defineProps<GlassColorSwatchProps>(), {
  selected: false,
  size: 'md',
});

const emit = defineEmits<{
  (e: 'click', color: string): void;
}>();

const justCopied = ref(false);

const sizeMap: Record<string, string> = {
  sm: 'h-6 w-6 rounded-md',
  md: 'h-8 w-8 rounded-lg',
  lg: 'h-10 w-10 rounded-xl',
};

const handleClick = async () => {
  try {
    await navigator.clipboard.writeText(props.color);
    justCopied.value = true;
    setTimeout(() => (justCopied.value = false), 1500);
  } catch { /* noop */ }
  emit('click', props.color);
};

const showCheck = computed(() => props.selected || justCopied.value);
</script>

<template>
  <button
    type="button"
    :title="color"
    :class="cn(
      'inline-flex items-center justify-center cursor-pointer border-2 transition-all duration-200',
      'hover:scale-110 hover:shadow-lg',
      'active:scale-95',
      'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent-primary,#3b82f6)] focus-visible:ring-offset-2',
      sizeMap[size],
      selected
        ? 'border-[var(--accent-primary,#3b82f6)] shadow-md'
        : 'border-[var(--surface-border,#e2e8f0)] dark:border-[rgba(255,255,255,0.15)]',
      $props.class,
    )"
    :style="{ backgroundColor: color }"
    @click="handleClick"
  >
    <svg
      v-if="showCheck"
      class="h-3.5 w-3.5 drop-shadow-md"
      :class="color.toLowerCase().includes('fff') || color.toLowerCase().includes('f8f') ? 'text-gray-800' : 'text-white'"
      fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3"
    >
      <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
    </svg>
  </button>
</template>

// packages/react/src/components/glassmorphic/glass-color-swatch/glass-color-swatch.tsx
'use client';

import * as React from 'react';
import { cn } from '@archui/core';

export interface GlassColorSwatchProps
    extends React.ButtonHTMLAttributes<HTMLButtonElement> {
    /** CSS color string */
    color: string;
    /** Label for the swatch */
    label?: string;
    /** Whether to show the label text */
    showLabel?: boolean;
    /** Whether this swatch is selected */
    selected?: boolean;
    /** Visual size */
    size?: 'sm' | 'md' | 'lg';
}

const sizeMap = {
    sm: 'h-6 w-6',
    md: 'h-8 w-8',
    lg: 'h-10 w-10',
};

/**
 * GlassColorSwatch — A clickable color swatch that copies the color value.
 *
 * @example
 * ```tsx
 * <GlassColorSwatch color="#f59e0b" label="Amber" showLabel selected />
 * ```
 */
export const GlassColorSwatch = React.forwardRef<
    HTMLButtonElement,
    GlassColorSwatchProps
>(
    (
        {
            color,
            label,
            showLabel = false,
            selected,
            size = 'md',
            className,
            onClick,
            ...props
        },
        ref,
    ) => {
        const [copied, setCopied] = React.useState(false);

        const handleClick = async (e: React.MouseEvent<HTMLButtonElement>) => {
            await navigator.clipboard.writeText(color);
            setCopied(true);
            setTimeout(() => setCopied(false), 1500);
            onClick?.(e);
        };

        return (
            <div className={cn('inline-flex flex-col items-center gap-1', className)}>
                <button
                    ref={ref}
                    onClick={handleClick}
                    type="button"
                    className={cn(
                        'relative rounded-lg border-2 transition-all duration-200',
                        sizeMap[size],
                        selected
                            ? 'border-[var(--accent-primary,#f59e0b)] ring-2 ring-[var(--accent-subtle,rgba(245,158,11,0.10))]'
                            : 'border-[var(--surface-border,#e2e8f0)] dark:border-[var(--surface-border,rgba(255,255,255,0.1))]',
                        'hover:scale-110 active:scale-95',
                        'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--glass-accent,#3b82f6)]',
                        'cursor-pointer',
                    )}
                    style={{ backgroundColor: color }}
                    aria-label={`Color ${label || color}. Click to copy.`}
                    title={copied ? 'Copied!' : `Copy ${color}`}
                    {...props}
                >
                    {(selected || copied) && (
                        <svg
                            className="absolute inset-0 m-auto h-3.5 w-3.5 text-white drop-shadow-md"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth={3}
                        >
                            <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                d="M5 13l4 4L19 7"
                            />
                        </svg>
                    )}
                </button>
                {showLabel && (
                    <span className="text-[10px] font-mono text-[var(--glass-text-muted,#94a3b8)]">
                        {label || color}
                    </span>
                )}
            </div>
        );
    },
);

GlassColorSwatch.displayName = 'GlassColorSwatch';
