// packages/vue/src/components/glassmorphic/GlassDrawer.vue
<script setup lang="ts">
import { cn } from '@archui/core';
import EffectContainer from '../../base/EffectContainer.vue';

interface Props {
  isOpen: boolean;
  class?: string;
}

defineProps<Props>();
const emit = defineEmits(['close']);
</script>

<template>
  <Teleport to="body">
    <Transition
      enter-active-class="transition-opacity duration-300 ease-out"
      enter-from-class="opacity-0"
      leave-active-class="transition-opacity duration-200 ease-in"
      leave-to-class="opacity-0"
    >
      <div v-if="isOpen" class="fixed inset-0 z-40 bg-black/20 backdrop-blur-[2px]" @click="emit('close')" />
    </Transition>

    <Transition
      enter-active-class="transition-all duration-500 cubic-bezier(0.34, 1.56, 0.64, 1)"
      enter-from-class="translate-x-full scale-x-90 opacity-0"
      leave-active-class="transition-all duration-300 ease-in"
      leave-to-class="translate-x-full opacity-0"
    >
      <div
        v-if="isOpen"
        :class="cn('fixed right-0 top-0 z-50 h-full w-full max-w-md shadow-2xl origin-right', $props.class)"
      >
        <EffectContainer class="h-full border-l border-surface-border bg-surface-primary/60 backdrop-blur-3xl">
          <template #effects>
            <div class="absolute inset-0 bg-gradient-to-l from-white/5 to-transparent pointer-events-none" />
          </template>
          <div class="flex flex-col h-full p-6 overflow-y-auto">
            <slot />
          </div>
        </EffectContainer>
      </div>
    </Transition>
  </Teleport>
</template>

// packages/react/src/components/glassmorphic/glass-drawer/glass-drawer.tsx
'use client';

import * as React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { cn } from '@archui/core';
import { EffectContainer } from '../../../base/effect-container';

interface GlassDrawerProps {
    isOpen: boolean;
    onClose: () => void;
    children: React.ReactNode;
    className?: string;
}

const GlassDrawer = ({ isOpen, onClose, children, className }: GlassDrawerProps) => {
    return (
        <AnimatePresence>
            {isOpen && (
                <>
                    {/* Backdrop */}
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        onClick={onClose}
                        className="fixed inset-0 z-40 bg-black/20 backdrop-blur-[2px]"
                    />

                    {/* Liquid Side Panel */}
                    <motion.div
                        initial={{ x: '100%', scaleX: 0.8, opacity: 0.5 }}
                        animate={{
                            x: 0,
                            scaleX: 1,
                            opacity: 1,
                            transition: {
                                type: 'spring',
                                stiffness: 300,
                                damping: 32,
                                mass: 1.2
                            }
                        }}
                        exit={{
                            x: '100%',
                            scaleX: 0.9,
                            opacity: 0,
                            transition: { duration: 0.3, ease: 'circIn' }
                        }}
                        className={cn(
                            'fixed right-0 top-0 z-50 h-full w-full max-w-md shadow-2xl origin-right',
                            className
                        )}
                    >
                        <EffectContainer
                            className="h-full border-l border-surface-border bg-surface-primary/60 backdrop-blur-3xl"
                            effects={
                                <div className="absolute inset-0 bg-gradient-to-l from-white/5 to-transparent pointer-events-none" />
                            }
                        >
                            <div className="flex flex-col h-full p-6 overflow-y-auto">
                                {children}
                            </div>
                        </EffectContainer>
                    </motion.div>
                </>
            )}
        </AnimatePresence>
    );
};

export { GlassDrawer };
