// packages/vue/src/components/glassmorphic/GlassStepper.vue
<script setup lang="ts">
/**
 * GlassStepper - Token-based multi-step progress flow for Vue 3
 */
import { computed } from 'vue';
import { cn } from '@archui/core';

interface StepItem {
  label: string;
  description?: string;
}

interface Props {
  steps: StepItem[];
  activeStep?: number;
  orientation?: 'horizontal' | 'vertical';
  class?: string;
}

const props = withDefaults(defineProps<Props>(), {
  activeStep: 0,
  orientation: 'horizontal',
});

const emit = defineEmits<{
  (e: 'stepClick', index: number): void;
}>();

const isVertical = computed(() => props.orientation === 'vertical');

const getStatus = (index: number) => {
  if (index < props.activeStep) return 'completed';
  if (index === props.activeStep) return 'active';
  return 'pending';
};
</script>

<template>
  <div :class="cn('flex', isVertical ? 'flex-col' : 'flex-row items-start', props.class)">
    <template v-for="(step, index) in steps" :key="index">
      <div :class="cn('flex shrink-0', isVertical ? 'flex-row items-start gap-3' : 'flex-col items-center gap-2')">
        <button type="button" :class="cn(
          'relative flex items-center justify-center rounded-full h-9 w-9 shrink-0 transition-all duration-300 ease-out outline-none',
          'focus-visible:ring-2 focus-visible:ring-[var(--glass-accent)]/30 focus-visible:ring-offset-2',
          getStatus(index) === 'completed' && 'bg-[var(--glass-success)] text-white shadow-[0_0_12px_var(--glass-success)]',
          getStatus(index) === 'active' && 'bg-[var(--glass-accent)] text-white shadow-[0_0_16px_var(--glass-accent)] animate-pulse',
          getStatus(index) === 'pending' && 'bg-[var(--glass-surface-hover)] text-[var(--glass-text-muted)] border border-[var(--glass-edge)]',
        )" @click="emit('stepClick', index)">
          <svg v-if="getStatus(index) === 'completed'" class="h-4 w-4" viewBox="0 0 24 24" fill="none"
            stroke="currentColor" stroke-width="2.5">
            <polyline points="20 6 9 17 4 12" />
          </svg>
          <span v-else class="text-xs font-semibold">{{ index + 1 }}</span>
        </button>
        <div :class="cn(isVertical ? 'pt-1' : 'text-center max-w-[100px]')">
          <p
            :class="cn('text-xs font-medium', getStatus(index) === 'pending' ? 'text-[var(--glass-text-muted)]' : 'text-[var(--glass-text-secondary)]')">
            {{ step.label }}
          </p>
          <p v-if="step.description" class="mt-0.5 text-[11px] text-[var(--glass-text-placeholder)] leading-tight">{{
            step.description }}</p>
        </div>
      </div>
      <div v-if="index !== steps.length - 1" :class="cn(
        'relative overflow-hidden rounded-full',
        isVertical ? 'ml-[17px] w-px h-8 my-1' : 'mt-[17px] h-px flex-1 min-w-[24px] mx-2',
        'bg-[var(--glass-divider)]',
      )">
        <div :class="cn(
          'absolute rounded-full bg-[var(--glass-success)]/60 transition-all duration-500 ease-out',
          isVertical ? 'top-0 left-0 w-full' : 'left-0 top-0 h-full',
        )"
          :style="isVertical ? { height: getStatus(index) === 'completed' ? '100%' : getStatus(index) === 'active' ? '50%' : '0%' } : { width: getStatus(index) === 'completed' ? '100%' : getStatus(index) === 'active' ? '50%' : '0%' }" />
      </div>
    </template>
  </div>
</template>

// apps/docs/src/pages/docs/components/glass-stepper.tsx
import { useState } from 'react';
import { GlassStepper } from '@archui/react';
import { ComponentPreview } from '../../../components/component-preview';

const steps = [
    { label: 'Account', description: 'Create your account' },
    { label: 'Profile', description: 'Set up your profile' },
    { label: 'Preferences', description: 'Configure settings' },
    { label: 'Complete', description: 'Ready to go' },
];

export function GlassStepperDocs() {
    const [activeStep, setActiveStep] = useState(1);

    return (
        <div className="space-y-6">
            <div>
                <h1 className="scroll-m-20 text-4xl font-bold tracking-tight text-[hsl(var(--foreground))]">Glass Stepper</h1>
                <p className="mt-4 text-lg text-[hsl(var(--muted-foreground))]">A multi-step progress flow with translucent nodes, glowing accents, and animated connector lines.</p>
            </div>
            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b border-[hsl(var(--border))] pb-2 text-2xl font-semibold tracking-tight text-[hsl(var(--foreground))]">Preview</h2>
                <ComponentPreview
                    code={`<GlassStepper steps={steps} activeStep={1} onStepClick={setActiveStep} />`}
                    vueCode={`<GlassStepper :steps="steps" :active-step="1" @step-click="setActiveStep" />`}
                >
                    <div className="w-full space-y-6">
                        <GlassStepper steps={steps} activeStep={activeStep} onStepClick={setActiveStep} />
                        <div className="flex items-center justify-center gap-2">
                            <button
                                className="px-3 py-1.5 rounded-lg text-sm text-slate-600 dark:text-white/60 bg-black/[0.04] dark:bg-white/[0.06] hover:bg-black/[0.06] dark:hover:bg-white/[0.08] transition-colors disabled:opacity-30"
                                onClick={() => setActiveStep(Math.max(0, activeStep - 1))}
                                disabled={activeStep <= 0}
                            >
                                Previous
                            </button>
                            <button
                                className="px-3 py-1.5 rounded-lg text-sm text-white bg-blue-500 hover:bg-blue-600 transition-colors disabled:opacity-30"
                                onClick={() => setActiveStep(Math.min(steps.length - 1, activeStep + 1))}
                                disabled={activeStep >= steps.length - 1}
                            >
                                Next
                            </button>
                        </div>
                    </div>
                </ComponentPreview>
            </div>
            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b border-[hsl(var(--border))] pb-2 text-2xl font-semibold tracking-tight text-[hsl(var(--foreground))]">Props</h2>
                <div className="overflow-x-auto">
                    <table className="w-full border-collapse text-sm">
                        <thead><tr className="border-b border-[hsl(var(--border))]"><th className="py-3 pr-4 text-left font-semibold text-[hsl(var(--foreground))]">Prop</th><th className="py-3 pr-4 text-left font-semibold text-[hsl(var(--foreground))]">Type</th><th className="py-3 pr-4 text-left font-semibold text-[hsl(var(--foreground))]">Default</th><th className="py-3 text-left font-semibold text-[hsl(var(--foreground))]">Description</th></tr></thead>
                        <tbody>
                            <tr className="border-b border-[hsl(var(--border))]"><td className="py-3 pr-4 text-[hsl(var(--foreground))]"><code>steps</code></td><td className="py-3 pr-4 text-[hsl(var(--muted-foreground))]">StepItem[]</td><td className="py-3 pr-4 text-[hsl(var(--muted-foreground))]">—</td><td className="py-3 text-[hsl(var(--muted-foreground))]">Step definitions</td></tr>
                            <tr className="border-b border-[hsl(var(--border))]"><td className="py-3 pr-4 text-[hsl(var(--foreground))]"><code>activeStep</code></td><td className="py-3 pr-4 text-[hsl(var(--muted-foreground))]">number</td><td className="py-3 pr-4 text-[hsl(var(--muted-foreground))]">0</td><td className="py-3 text-[hsl(var(--muted-foreground))]">Currently active step (0-indexed)</td></tr>
                            <tr className="border-b border-[hsl(var(--border))]"><td className="py-3 pr-4 text-[hsl(var(--foreground))]"><code>orientation</code></td><td className="py-3 pr-4 text-[hsl(var(--muted-foreground))]">'horizontal' | 'vertical'</td><td className="py-3 pr-4 text-[hsl(var(--muted-foreground))]">'horizontal'</td><td className="py-3 text-[hsl(var(--muted-foreground))]">Layout orientation</td></tr>
                            <tr className="border-b border-[hsl(var(--border))]"><td className="py-3 pr-4 text-[hsl(var(--foreground))]"><code>onStepClick</code></td><td className="py-3 pr-4 text-[hsl(var(--muted-foreground))]">(index: number) =&gt; void</td><td className="py-3 pr-4 text-[hsl(var(--muted-foreground))]">—</td><td className="py-3 text-[hsl(var(--muted-foreground))]">Click-to-navigate callback</td></tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    );
}
