// packages/vue/src/components/glassmorphic/GlassToggleGroup.vue
<script setup lang="ts">
/**
 * GlassToggleGroup - Grouped toggle set with single/multiple select
 */

import { cn } from '@archui/core';

interface GlassToggleGroupProps {
  modelValue: string | string[];
  type?: 'single' | 'multiple';
  class?: string;
}

const props = withDefaults(defineProps<GlassToggleGroupProps>(), {
  type: 'single',
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: string | string[]): void;
}>();

const slots = defineSlots<{ default?(): any }>();

const isSelected = (val: string) => {
  if (props.type === 'multiple') {
    return Array.isArray(props.modelValue) && props.modelValue.includes(val);
  }
  return props.modelValue === val;
};

const toggle = (val: string) => {
  if (props.type === 'multiple') {
    const arr = Array.isArray(props.modelValue) ? [...props.modelValue] : [];
    const idx = arr.indexOf(val);
    if (idx >= 0) arr.splice(idx, 1);
    else arr.push(val);
    emit('update:modelValue', arr);
  } else {
    emit('update:modelValue', props.modelValue === val ? '' : val);
  }
};

defineExpose({ isSelected, toggle });
</script>

<template>
  <div
    role="group"
    :class="cn(
      'inline-flex items-center gap-1 rounded-xl p-1',
      'bg-[var(--surface-bg-hover,#f1f5f9)] dark:bg-[var(--glass-bg-dark,rgba(255,255,255,0.03))]',
      'border border-[var(--surface-border,#e2e8f0)] dark:border-[var(--surface-border,rgba(255,255,255,0.08))]',
      $props.class,
    )"
  >
    <slot :is-selected="isSelected" :toggle="toggle" />
  </div>
</template>

// packages/react/src/components/glassmorphic/glass-toggle-group/glass-toggle-group.tsx
'use client';

import * as React from 'react';
import { cn } from '@archui/core';
import { GlassToggle } from '../glass-toggle/glass-toggle';

export interface GlassToggleGroupItem {
    value: string;
    label: React.ReactNode;
    disabled?: boolean;
}

export interface GlassToggleGroupProps {
    /** Items to render as toggles */
    items: GlassToggleGroupItem[];
    /** 'single' = radio behaviour, 'multiple' = checkbox behaviour */
    type?: 'single' | 'multiple';
    /** Controlled value (string for single, string[] for multiple) */
    value?: string | string[];
    /** Callback on value change */
    onValueChange?: (value: string | string[]) => void;
    /** Toggle button size */
    size?: 'sm' | 'md' | 'lg';
    /** Additional CSS classes on the group wrapper */
    className?: string;
}

/**
 * GlassToggleGroup — Grouped set of toggle buttons.
 *
 * Supports single (radio) and multiple (checkbox) selection modes.
 * Used for filter bars, view mode selectors, and settings panels.
 *
 * @example
 * ```tsx
 * <GlassToggleGroup
 *   type="single"
 *   value={view}
 *   onValueChange={setView}
 *   items={[
 *     { value: 'grid', label: <Grid className="h-4 w-4" /> },
 *     { value: 'list', label: <List className="h-4 w-4" /> },
 *   ]}
 * />
 * ```
 */
export function GlassToggleGroup({
    items,
    type = 'single',
    value,
    onValueChange,
    size = 'md',
    className,
}: GlassToggleGroupProps) {
    const handleToggle = (itemValue: string) => {
        if (type === 'single') {
            onValueChange?.(itemValue);
        } else {
            const current = Array.isArray(value) ? value : [];
            const next = current.includes(itemValue)
                ? current.filter((v) => v !== itemValue)
                : [...current, itemValue];
            onValueChange?.(next);
        }
    };

    const isPressed = (itemValue: string): boolean => {
        if (type === 'single') return value === itemValue;
        return Array.isArray(value) && value.includes(itemValue);
    };

    return (
        <div
            className={cn(
                'inline-flex items-center gap-1 rounded-xl p-1',
                'bg-[var(--surface-bg-subtle,#f8fafc)]',
                'dark:bg-[var(--glass-bg-dark,rgba(255,255,255,0.05))]',
                'border border-[var(--surface-border,#e2e8f0)]',
                'dark:border-[var(--surface-border,rgba(255,255,255,0.1))]',
                className,
            )}
            role="group"
        >
            {items.map((item) => (
                <GlassToggle
                    key={item.value}
                    pressed={isPressed(item.value)}
                    onPressedChange={() => handleToggle(item.value)}
                    size={size}
                    disabled={item.disabled}
                >
                    {item.label}
                </GlassToggle>
            ))}
        </div>
    );
}
