// packages/vue/src/components/glassmorphic/GlassLoginForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { Mail, Lock } from 'lucide-vue-next';
import GlassCard from './GlassCard.vue';
import GlassButton from './GlassButton.vue';
import GlassInput from './GlassInput.vue';

interface Props {
  title?: string;
  subtitle?: string;
  socialLayout?: 'horizontal' | 'vertical';
  loading?: boolean;
}

const props = withDefaults(defineProps<Props>(), {
  title: 'Welcome Back',
  subtitle: 'Sign in to your account to continue',
  socialLayout: 'horizontal',
  loading: false,
});

const emit = defineEmits<{
  (e: 'submit', data: any): void;
  (e: 'forgot-password'): void;
  (e: 'sign-up'): void;
}>();

const email = ref('');
const password = ref('');

const handleSubmit = () => {
  emit('submit', { email: email.value, password: password.value });
};
</script>

<template>
  <GlassCard
    class="w-full max-w-[420px] mx-auto p-8 sm:p-10 bg-white/60 dark:bg-black/40 border-white/40 dark:border-white/10"
    variant="default"
    :animated="false"
    shine
  >
    <!-- Header -->
    <div class="flex flex-col items-center text-center mb-10">
      <h2 class="text-3xl font-bold tracking-tight text-form-text mb-3">
        {{ props.title }}
      </h2>
      <p class="text-base text-form-helper max-w-[280px]">
        {{ props.subtitle }}
      </p>
    </div>

    <form @submit.prevent="handleSubmit" class="space-y-6">
      <div class="space-y-5">
        <GlassInput
          id="email"
          type="email"
          placeholder="name@example.com"
          label="Email address"
          v-model="email"
          required
          class="bg-form-bg focus:bg-form-bg-focus dark:bg-white/5 dark:focus:bg-white/10"
        >
          <template #leftIcon>
            <Mail class="w-4 h-4 text-form-placeholder" />
          </template>
        </GlassInput>

        <div class="space-y-2">
          <GlassInput
            id="password"
            type="password"
            placeholder="********"
            label="Password"
            v-model="password"
            required
            class="bg-form-bg focus:bg-form-bg-focus dark:bg-white/5 dark:focus:bg-white/10"
          >
            <template #leftIcon>
              <Lock class="w-4 h-4 text-form-placeholder" />
            </template>
          </GlassInput>
          <div class="flex justify-end">
            <button
              type="button"
              @click="$emit('forgot-password')"
              class="text-xs font-medium text-form-helper hover:text-primary transition-colors hover:underline underline-offset-4"
            >
              Forgot your password?
            </button>
          </div>
        </div>
      </div>

      <GlassButton
        type="submit"
        variant="primary"
        class="w-full font-semibold tracking-wide shadow-lg shadow-primary/25 hover:shadow-primary/40"
        size="lg"
        glow
        :disabled="props.loading"
      >
        {{ props.loading ? 'Signing in...' : 'Sign in' }}
      </GlassButton>
    </form>

    <div class="my-8 flex items-center gap-4">
      <div class="h-px bg-form-border flex-1 opacity-50"></div>
      <span class="text-xs font-medium text-form-placeholder uppercase tracking-wider">Or continue with</span>
      <div class="h-px bg-form-border flex-1 opacity-50"></div>
    </div>

    <div
      :class="[
        'grid gap-4',
        props.socialLayout === 'horizontal' ? 'grid-cols-2' : 'grid-cols-1'
      ]"
    >
      <GlassButton
        variant="outline"
        class="w-full border-form-border/50 hover:bg-form-bg-hover dark:hover:bg-white/5"
      >
        <template #leftIcon>
          <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
            <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
          </svg>
        </template>
        GitHub
      </GlassButton>
      <GlassButton
        variant="outline"
        class="w-full border-form-border/50 hover:bg-form-bg-hover dark:hover:bg-white/5"
      >
        <template #leftIcon>
          <svg class="h-5 w-5" viewBox="0 0 24 24">
            <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4"/>
            <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/>
            <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05"/>
            <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/>
          </svg>
        </template>
        Google
      </GlassButton>
    </div>

    <div class="mt-8 flex items-center justify-center gap-1 text-sm">
      <span class="text-form-helper">Don't have an account? </span>
      <button
        type="button"
        @click="$emit('sign-up')"
        class="font-semibold text-form-text hover:text-primary transition-colors hover:underline"
      >
        Sign up
      </button>
    </div>
  </GlassCard>
</template>

// packages/react/src/components/glassmorphic/glass-login-form/glass-login-form.tsx
'use client';

import * as React from 'react';
import { cn } from '@archui/core';
import { Mail, Lock } from 'lucide-react';
import { GlassCard } from '../glass-card';
import { GlassButton } from '../glass-button';
import { GlassInput } from '../glass-input';
import { GlassSeparator } from '../glass-separator';
import { GitHubIcon, GoogleIcon } from './icons';

export interface GlassLoginFormProps extends React.HTMLAttributes<HTMLDivElement> {
    /** Callback when form is submitted */
    onSubmit?: (data: any) => void;
    /** Callback for forgot password click */
    onForgotPassword?: () => void;
    /** Callback for sign up click */
    onSignUp?: () => void;
    /** Title of the form */
    title?: string;
    /** Subtitle/description */
    subtitle?: string;
    /** Optional logo element */
    logo?: React.ReactNode;
    /** Layout for social buttons */
    socialLayout?: 'horizontal' | 'vertical';
    /** Loading state */
    loading?: boolean;
}

/**
 * GlassLoginForm - A premium glassmorphic login form
 * 
 * Features:
 * - Built on GlassCard for beautiful glass effect
 * - Integrated GlassInput and GlassButton components
 * - Social login support
 * - Responsive design
 */
export function GlassLoginForm({
    className,
    onSubmit,
    onForgotPassword,
    onSignUp,
    title = "Welcome Back",
    subtitle = "Sign in to your account to continue",
    logo,
    socialLayout = 'horizontal',
    loading = false,
    ...props
}: GlassLoginFormProps) {
    const [email, setEmail] = React.useState('');
    const [password, setPassword] = React.useState('');

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        onSubmit?.({ email, password });
    };

    return (
        <GlassCard
            className={cn(
                "w-full max-w-[420px] mx-auto p-8 sm:p-10",
                "bg-surface-glass backdrop-blur-3xl", // Hybrid: Organic Smoothness
                "border-surface-glass-border",
                "shadow-[inset_0_1px_1px_rgba(255,255,255,0.1),0_8px_32px_rgba(0,0,0,0.12)]", // Hybrid: Luxury Edge
                className
            )}
            variant="elevated"
            animated={false}
            shine
            {...props}
        >
            {/* Header */}
            <div className="flex flex-col items-center text-center mb-10">
                {logo && <div className="mb-6 scale-110">{logo}</div>}
                <h2 className="text-3xl font-semibold tracking-tight text-text-primary mb-3">
                    {title}
                </h2>
                <p className="text-base text-text-secondary max-w-[280px]">
                    {subtitle}
                </p>
            </div>

            <form onSubmit={handleSubmit} className="space-y-6">
                <div className="space-y-5">
                    <GlassInput
                        id="email"
                        type="email"
                        placeholder="name@example.com"
                        label="Email address"
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        required
                        leftIcon={<Mail className="w-4 h-4 text-text-muted" />}
                        className="bg-surface-elevated focus:bg-surface-hover transition-colors duration-300"
                    />
                    <div className="space-y-2">
                        <GlassInput
                            id="password"
                            type="password"
                            placeholder="********"
                            label="Password"
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                            required
                            leftIcon={<Lock className="w-4 h-4 text-text-muted" />}
                            className="bg-surface-elevated focus:bg-surface-hover transition-colors duration-300"
                        />
                        {onForgotPassword && (
                            <div className="flex justify-end">
                                <button
                                    type="button"
                                    onClick={onForgotPassword}
                                    className="text-xs font-medium text-text-secondary hover:text-interactive-primary transition-colors duration-300 hover:underline underline-offset-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring-focus rounded-sm"
                                >
                                    Forgot your password?
                                </button>
                            </div>
                        )}
                    </div>
                </div>

                <GlassButton
                    type="submit"
                    variant="primary"
                    className="w-full font-semibold tracking-wide shadow-lg shadow-interactive-primary/25 hover:shadow-interactive-primary/40 transition-all duration-500 [transition-timing-function:cubic-bezier(0.22,1,0.36,1)]"
                    size="lg"
                    glow
                    disabled={loading}
                >
                    {loading ? 'Signing in...' : 'Sign in'}
                </GlassButton>
            </form>

            <div className="my-8 flex items-center gap-4">
                <GlassSeparator className="flex-1 opacity-50" />
                {/* Hybrid: Industrial Clarity */}
                <span className="text-[10px] font-mono font-semibold text-text-muted uppercase tracking-[0.2em]">Or continue with</span>
                <GlassSeparator className="flex-1 opacity-50" />
            </div>

            <div className={cn(
                "grid gap-4",
                socialLayout === 'horizontal' ? "grid-cols-2" : "grid-cols-1"
            )}>
                <GlassButton
                    variant="outline"
                    className="w-full border-border-subtle hover:bg-surface-hover transition-colors duration-300"
                    leftIcon={<GitHubIcon />}
                >
                    GitHub
                </GlassButton>
                <GlassButton
                    variant="outline"
                    className="w-full border-border-subtle hover:bg-surface-hover transition-colors duration-300"
                    leftIcon={<GoogleIcon />}
                >
                    Google
                </GlassButton>
            </div>

            {onSignUp && (
                <div className="mt-8 flex items-center justify-center gap-1.5 text-sm">
                    <span className="text-text-secondary">Don't have an account? </span>
                    <button
                        type="button"
                        onClick={onSignUp}
                        className="font-semibold text-text-primary hover:text-interactive-primary transition-colors duration-300 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring-focus rounded-sm px-1 py-0.5"
                    >
                        Sign up
                    </button>
                </div>
            )}
        </GlassCard>
    );
}
