// packages/react/src/components/glassmorphic/glass-slider/glass-slider.tsx
'use client';

import * as React from 'react';
import { cn } from '@archui/core';

export interface GlassSliderProps
    extends Omit<
        React.InputHTMLAttributes<HTMLInputElement>,
        'value' | 'onChange' | 'type' | 'size'
    > {
    /** Current value */
    value?: number;
    /** Default value (uncontrolled) */
    defaultValue?: number;
    /** Minimum value */
    min?: number;
    /** Maximum value */
    max?: number;
    /** Step size */
    step?: number;
    /** Callback on value change */
    onChange?: (value: number) => void;
    /** Show value tooltip on thumb drag */
    showTooltip?: boolean;
    /** Visual size */
    size?: 'sm' | 'md' | 'lg';
    /** Label text */
    label?: string;
}

const trackHeight = { sm: 'h-1', md: 'h-1.5', lg: 'h-2' };

/**
 * GlassSlider — Range input with glass-styled track and thumb.
 *
 * Supports single value selection with real-time fill track and optional
 * tooltip on thumb drag.
 *
 * @example
 * ```tsx
 * <GlassSlider label="Volume" value={volume} onChange={setVolume} />
 * ```
 */
export function GlassSlider({
    value: controlledValue,
    defaultValue = 50,
    min = 0,
    max = 100,
    step = 1,
    onChange,
    showTooltip = false,
    size = 'md',
    label,
    className,
    disabled,
    ...props
}: GlassSliderProps) {
    const [internalValue, setInternalValue] = React.useState(defaultValue);
    const [isDragging, setIsDragging] = React.useState(false);
    const value = controlledValue ?? internalValue;
    const percentage = ((value - min) / (max - min)) * 100;

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const newValue = Number(e.target.value);
        setInternalValue(newValue);
        onChange?.(newValue);
    };

    return (
        <div className={cn('w-full', className)}>
            {label && (
                <div className="flex items-center justify-between mb-2">
                    <label className="text-sm font-medium text-[var(--glass-text,#0f172a)] dark:text-[var(--glass-text,#f8fafc)]">
                        {label}
                    </label>
                    <span className="text-sm text-[var(--glass-text-muted,#94a3b8)] tabular-nums">
                        {value}
                    </span>
                </div>
            )}
            <div className="relative flex items-center">
                {/* Track background */}
                <div
                    className={cn(
                        'absolute w-full rounded-full',
                        trackHeight[size],
                        'bg-[var(--surface-bg-hover,#f1f5f9)]',
                        'dark:bg-[var(--glass-bg-dark,rgba(255,255,255,0.05))]',
                        'border border-[var(--surface-border,#e2e8f0)]',
                        'dark:border-[var(--surface-border,rgba(255,255,255,0.1))]',
                    )}
                />
                {/* Fill track */}
                <div
                    className={cn(
                        'absolute rounded-full pointer-events-none',
                        trackHeight[size],
                        'bg-[var(--accent-primary,#f59e0b)]',
                        'transition-[width] duration-75',
                    )}
                    style={{ width: `${percentage}%` }}
                />
                {/* Native input */}
                <input
                    type="range"
                    min={min}
                    max={max}
                    step={step}
                    value={value}
                    onChange={handleChange}
                    onMouseDown={() => setIsDragging(true)}
                    onMouseUp={() => setIsDragging(false)}
                    onTouchStart={() => setIsDragging(true)}
                    onTouchEnd={() => setIsDragging(false)}
                    disabled={disabled}
                    className={cn(
                        'relative z-10 w-full appearance-none bg-transparent cursor-pointer',
                        // Webkit thumb
                        '[&::-webkit-slider-thumb]:appearance-none',
                        '[&::-webkit-slider-thumb]:h-4 [&::-webkit-slider-thumb]:w-4',
                        '[&::-webkit-slider-thumb]:rounded-full',
                        '[&::-webkit-slider-thumb]:bg-white',
                        '[&::-webkit-slider-thumb]:border-2',
                        '[&::-webkit-slider-thumb]:border-[var(--accent-primary,#f59e0b)]',
                        '[&::-webkit-slider-thumb]:shadow-md',
                        '[&::-webkit-slider-thumb]:transition-transform',
                        '[&::-webkit-slider-thumb]:duration-[var(--duration-fast,120ms)]',
                        '[&::-webkit-slider-thumb]:hover:scale-110',
                        '[&::-webkit-slider-thumb]:active:scale-95',
                        // Dark thumb
                        'dark:[&::-webkit-slider-thumb]:bg-[var(--surface-bg-hover,rgba(255,255,255,0.08))]',
                        // Firefox thumb
                        '[&::-moz-range-thumb]:appearance-none',
                        '[&::-moz-range-thumb]:h-4 [&::-moz-range-thumb]:w-4',
                        '[&::-moz-range-thumb]:rounded-full',
                        '[&::-moz-range-thumb]:bg-white',
                        '[&::-moz-range-thumb]:border-2',
                        '[&::-moz-range-thumb]:border-[var(--accent-primary,#f59e0b)]',
                        '[&::-moz-range-thumb]:shadow-md',
                        // Disabled
                        disabled && 'opacity-40 cursor-not-allowed',
                    )}
                    aria-label={label}
                    {...props}
                />
                {/* Tooltip */}
                {showTooltip && isDragging && (
                    <div
                        className={cn(
                            'absolute -top-9 px-2 py-1 rounded-md text-xs font-semibold',
                            'bg-[var(--surface-bg,#ffffff)]',
                            'text-[var(--glass-text,#0f172a)]',
                            'dark:bg-[var(--glass-bg-dark,rgba(255,255,255,0.05))]',
                            'dark:text-[var(--glass-text,#f8fafc)]',
                            'dark:backdrop-blur-xl',
                            'border border-[var(--surface-border,#e2e8f0)]',
                            'dark:border-[var(--surface-border,rgba(255,255,255,0.1))]',
                            'shadow-lg',
                            'pointer-events-none tabular-nums',
                        )}
                        style={{
                            left: `${percentage}%`,
                            transform: 'translateX(-50%)',
                        }}
                    >
                        {value}
                    </div>
                )}
            </div>
        </div>
    );
}

// packages/vue/src/components/glassmorphic/GlassSlider.vue
<script setup lang="ts">
/**
 * GlassSlider - Range input with glass styling
 */
import { computed, ref } from 'vue';
import { cn } from '@archui/core';

interface GlassSliderProps {
  modelValue?: number;
  min?: number;
  max?: number;
  step?: number;
  disabled?: boolean;
  showTooltip?: boolean;
  class?: string;
}

const props = withDefaults(defineProps<GlassSliderProps>(), {
  modelValue: 0,
  min: 0,
  max: 100,
  step: 1,
  disabled: false,
  showTooltip: false,
});

const emit = defineEmits<{
  (e: 'update:modelValue', value: number): void;
}>();

const hovering = ref(false);
const pct = computed(() => ((props.modelValue - props.min) / (props.max - props.min)) * 100);

const onInput = (e: Event) => {
  const val = Number((e.target as HTMLInputElement).value);
  emit('update:modelValue', val);
};
</script>

<template>
  <div
    :class="cn('relative w-full group', disabled && 'opacity-40', $props.class)"
    @mouseenter="hovering = true"
    @mouseleave="hovering = false"
  >
    <!-- Tooltip -->
    <div
      v-if="showTooltip && hovering && !disabled"
      class="absolute -top-8 px-2 py-0.5 rounded-md text-xs font-medium pointer-events-none
        bg-[var(--glass-text,#0f172a)] dark:bg-[var(--glass-text,#f8fafc)]
        text-white dark:text-[#0f172a] transition-opacity duration-150"
      :style="{ left: `${pct}%`, transform: 'translateX(-50%)' }"
    >
      {{ modelValue }}
    </div>

    <!-- Track background -->
    <div class="relative h-2 w-full rounded-full bg-[var(--surface-bg-hover,#e2e8f0)] dark:bg-[rgba(255,255,255,0.08)]">
      <!-- Fill -->
      <div
        class="absolute h-full rounded-full bg-[var(--accent-primary,#3b82f6)] transition-all duration-100"
        :style="{ width: `${pct}%` }"
      />
    </div>

    <!-- Native range input (invisible, overlaid) -->
    <input
      type="range"
      :min="min"
      :max="max"
      :step="step"
      :value="modelValue"
      :disabled="disabled"
      :class="cn(
        'absolute inset-0 w-full h-2 opacity-0 cursor-pointer',
        disabled && 'cursor-not-allowed',
      )"
      @input="onInput"
    />

    <!-- Custom thumb (visual only) -->
    <div
      class="absolute top-1/2 -translate-y-1/2 h-4 w-4 rounded-full pointer-events-none
        bg-[var(--accent-primary,#3b82f6)] border-2 border-white dark:border-[#1e1e1e]
        shadow-md transition-transform duration-150
        group-hover:scale-110"
      :style="{ left: `calc(${pct}% - 8px)` }"
    />
  </div>
</template>
