// packages/react/src/components/glassmorphic/glass-theme-toggle/glass-theme-toggle.tsx
'use client';

import * as React from 'react';
import { cn } from '@archui/core';
import { Moon, Sun } from 'lucide-react';

export interface GlassThemeToggleProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
    onThemeChange?: (theme: 'light' | 'dark') => void;
    initialTheme?: 'light' | 'dark';
}

export function GlassThemeToggle({
    className,
    onThemeChange,
    initialTheme = 'light',
    ...props
}: GlassThemeToggleProps) {
    const [theme, setTheme] = React.useState<'light' | 'dark'>(initialTheme);

    const toggleTheme = () => {
        const newTheme = theme === 'light' ? 'dark' : 'light';
        setTheme(newTheme);
        onThemeChange?.(newTheme);

        // Toggle class on document
        if (newTheme === 'dark') {
            document.documentElement.classList.add('dark');
        } else {
            document.documentElement.classList.remove('dark');
        }
    };

    return (
        <button
            onClick={toggleTheme}
            className={cn(
                'group relative flex h-10 w-10 items-center justify-center rounded-xl',
                'bg-white/80 dark:bg-white/[0.06]',
                'backdrop-blur-md',
                'border border-black/[0.08] dark:border-white/[0.08]',
                'shadow-[0_2px_4px_rgba(0,0,0,0.02),0_1px_0_rgba(255,255,255,0.5)_inset]',
                'transition-all duration-300 ease-[cubic-bezier(0.34,1.56,0.64,1)]',
                'hover:bg-white/90 dark:hover:bg-white/[0.1]',
                'hover:shadow-[0_4px_12px_rgba(0,0,0,0.05)]',
                'hover:-translate-y-[1px]',
                'active:scale-90',
                className
            )}
            aria-label="Toggle theme"
            {...props}
        >
            <Sun
                className={cn(
                    "h-[1.2rem] w-[1.2rem] transition-all duration-300 absolute",
                    theme === 'dark' ? "scale-0 rotate-90 opacity-0" : "scale-100 rotate-0 opacity-100 text-amber-500"
                )}
            />
            <Moon
                className={cn(
                    "h-[1.2rem] w-[1.2rem] transition-all duration-300 absolute",
                    theme === 'light' ? "scale-0 -rotate-90 opacity-0" : "scale-100 rotate-0 opacity-100 text-blue-400"
                )}
            />
        </button>
    );
}

// packages/vue/src/components/glassmorphic/GlassThemeToggle.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { cn } from '@archui/core';

interface GlassThemeToggleProps {
  initialTheme?: 'light' | 'dark';
  class?: string;
}

const props = withDefaults(defineProps<GlassThemeToggleProps>(), {
  initialTheme: 'light',
});

const theme = ref<'light' | 'dark'>(props.initialTheme);

onMounted(() => {
  // Sync with document on mount if needed, or rely on internal state
  if (document.documentElement.classList.contains('dark')) {
      theme.value = 'dark';
  }
});

const toggleTheme = () => {
  theme.value = theme.value === 'light' ? 'dark' : 'light';
  
  if (theme.value === 'dark') {
    document.documentElement.classList.add('dark');
  } else {
    document.documentElement.classList.remove('dark');
  }
};
</script>

<template>
  <button
    @click="toggleTheme"
    :class="cn(
      'group relative flex h-10 w-10 items-center justify-center rounded-xl',
      // Light theme - visible background and border
      'bg-white/60 dark:bg-white/[0.06]',
      'backdrop-blur-md',
      'border border-black/[0.08] dark:border-white/[0.08]',
      'shadow-sm',
      'transition-all duration-300',
      'hover:bg-white/80 dark:hover:bg-white/[0.1]',
      'hover:shadow-md',
      'hover:-translate-y-0.5',
      'active:scale-95',
      props.class
    )"
    aria-label="Toggle theme"
  >
    <!-- Sun Icon -->
    <svg 
      xmlns="http://www.w3.org/2000/svg" 
      width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
      :class="cn(
        'h-[1.2rem] w-[1.2rem] transition-all duration-300 absolute text-amber-500',
        theme === 'dark' ? 'scale-0 rotate-90 opacity-0' : 'scale-100 rotate-0 opacity-100'
      )"
    >
      <circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/>
    </svg>

    <!-- Moon Icon -->
    <svg 
      xmlns="http://www.w3.org/2000/svg" 
      width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
      :class="cn(
        'h-[1.2rem] w-[1.2rem] transition-all duration-300 absolute text-blue-400',
        theme === 'light' ? 'scale-0 -rotate-90 opacity-0' : 'scale-100 rotate-0 opacity-100'
      )"
    >
      <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/>
    </svg>
  </button>
</template>
