// packages/react/src/components/foundation/glass-root/glass-root.tsx
'use client';

import * as React from 'react';
import { cn } from '@archui/core';

/**
 * Supported accent themes — single-hue palettes following the Anti-Gradient Manifesto
 */
export type AccentTheme = 'ember' | 'graphite' | 'slate' | 'sage' | 'crimson' | 'dusk' | 'iron';
export type ThemeMode = 'light' | 'dark' | 'system';

export interface GlassRootContextValue {
    mode: 'light' | 'dark';
    accent: AccentTheme;
    setMode: (mode: ThemeMode) => void;
    setAccent: (accent: AccentTheme) => void;
}

const GlassRootContext = React.createContext<GlassRootContextValue | null>(null);

/**
 * Hook to access the GlassRoot theme context
 * @throws If used outside <GlassRoot>
 */
export function useGlassRoot(): GlassRootContextValue {
    const ctx = React.useContext(GlassRootContext);
    if (!ctx) throw new Error('useGlassRoot must be used within <GlassRoot>');
    return ctx;
}

export interface GlassRootProps {
    children: React.ReactNode;
    /** Initial theme mode. Defaults to 'system'. */
    defaultMode?: ThemeMode;
    /** Initial accent theme. Defaults to 'ember'. */
    defaultAccent?: AccentTheme;
    /** Additional CSS classes on the wrapper */
    className?: string;
}

/**
 * GlassRoot — Universal theme provider for ArchUI.
 *
 * Wraps the entire app and injects the accent color CSS tokens
 * into the document root. Manages system vs forced dark/light mode.
 *
 * @example
 * ```tsx
 * <GlassRoot defaultMode="system" defaultAccent="ember">
 *   <App />
 * </GlassRoot>
 * ```
 */
export function GlassRoot({
    children,
    defaultMode = 'system',
    defaultAccent = 'ember',
    className,
}: GlassRootProps) {
    const [accent, setAccent] = React.useState<AccentTheme>(defaultAccent);
    const [resolvedMode, setResolvedMode] = React.useState<'light' | 'dark'>('light');
    const [requestedMode, setRequestedMode] = React.useState<ThemeMode>(defaultMode);

    // Resolve system theme
    React.useEffect(() => {
        if (requestedMode !== 'system') {
            setResolvedMode(requestedMode);
            return;
        }
        if (typeof window === 'undefined') return;
        const mql = window.matchMedia('(prefers-color-scheme: dark)');
        setResolvedMode(mql.matches ? 'dark' : 'light');
        const handler = (e: MediaQueryListEvent) => setResolvedMode(e.matches ? 'dark' : 'light');
        mql.addEventListener('change', handler);
        return () => mql.removeEventListener('change', handler);
    }, [requestedMode]);

    // Apply to <html> element
    React.useEffect(() => {
        const root = document.documentElement;
        root.classList.remove('light', 'dark');
        root.classList.add(resolvedMode);
        root.setAttribute('data-accent', accent);
    }, [resolvedMode, accent]);

    const ctx: GlassRootContextValue = React.useMemo(
        () => ({
            mode: resolvedMode,
            accent,
            setMode: setRequestedMode,
            setAccent,
        }),
        [resolvedMode, accent]
    );

    return (
        <GlassRootContext.Provider value={ctx}>
            <div
                className={cn('glass-root', className)}
                data-theme={resolvedMode}
                data-accent={accent}
            >
                {children}
            </div>
        </GlassRootContext.Provider>
    );
}

// packages/vue/src/components/glassmorphic/GlassRoot.vue
<script setup lang="ts">
/**
 * GlassRoot - Universal theme provider managing dark/light mode + accent color
 */
import { ref, provide, watch, onMounted, computed } from 'vue';

export type ThemeMode = 'light' | 'dark' | 'system';
export type AccentTheme = 'default' | 'ember' | 'graphite' | 'slate' | 'sage' | 'crimson' | 'dusk' | 'iron';

interface GlassRootProps {
  defaultMode?: ThemeMode;
  defaultAccent?: AccentTheme;
  class?: string;
}

const props = withDefaults(defineProps<GlassRootProps>(), {
  defaultMode: 'system',
  defaultAccent: 'default',
});

const mode = ref<ThemeMode>(props.defaultMode);
const accent = ref<AccentTheme>(props.defaultAccent);

const resolvedDark = computed(() => {
  if (mode.value === 'system') {
    return typeof window !== 'undefined' && window.matchMedia('(prefers-color-scheme: dark)').matches;
  }
  return mode.value === 'dark';
});

const applyTheme = () => {
  const el = document.documentElement;
  el.classList.toggle('dark', resolvedDark.value);
  el.classList.toggle('light', !resolvedDark.value);

  if (accent.value !== 'default') {
    el.setAttribute('data-accent', accent.value);
  } else {
    el.removeAttribute('data-accent');
  }
};

watch([mode, accent], applyTheme, { immediate: false });

onMounted(() => {
  applyTheme();
  if (mode.value === 'system') {
    const mq = window.matchMedia('(prefers-color-scheme: dark)');
    mq.addEventListener('change', applyTheme);
  }
});

const setMode = (m: ThemeMode) => { mode.value = m; };
const setAccent = (a: AccentTheme) => { accent.value = a; };

provide('glass-root', { mode, accent, resolvedDark, setMode, setAccent });

defineExpose({ mode, accent, resolvedDark, setMode, setAccent });
</script>

<template>
  <div :class="$props.class">
    <slot />
  </div>
</template>
