// packages/react/src/components/glassmorphic/glass-kbd/glass-kbd.tsx
'use client';

import * as React from 'react';
import { cn } from '@archui/core';

export interface GlassKbdProps extends React.HTMLAttributes<HTMLElement> {
    /** Key combination, e.g. "⌘K" or ["Ctrl", "Shift", "P"] */
    keys?: string | string[];
}

/**
 * GlassKbd — Keyboard shortcut display component.
 *
 * Renders keycap-styled elements with a subtle inset shadow
 * to mimic physical key depth. Used in tooltips, command
 * palettes, and documentation.
 *
 * @example
 * ```tsx
 * <GlassKbd keys={["⌘", "K"]} />
 * <GlassKbd keys="Esc" />
 * ```
 */
export const GlassKbd = React.forwardRef<HTMLElement, GlassKbdProps>(
    ({ className, keys, children, ...props }, ref) => {
        const renderKeys = () => {
            if (keys) {
                const keyArray = Array.isArray(keys) ? keys : [keys];
                return keyArray.map((key, i) => (
                    <React.Fragment key={i}>
                        {i > 0 && (
                            <span className="text-[var(--glass-text-muted,#94a3b8)] mx-0.5 text-[10px]">
                                +
                            </span>
                        )}
                        <kbd
                            className={cn(
                                'inline-flex h-5 min-w-[20px] items-center justify-center rounded px-1.5',
                                'text-[11px] font-medium font-mono leading-none',
                                // Light
                                'bg-[var(--surface-bg-subtle,#f8fafc)]',
                                'text-[var(--glass-text-secondary,#475569)]',
                                'border border-[var(--surface-border,#e2e8f0)]',
                                'shadow-[0_1px_0_1px_var(--surface-border,#e2e8f0)]',
                                // Dark
                                'dark:bg-[var(--surface-bg-hover,rgba(255,255,255,0.08))]',
                                'dark:text-[var(--glass-text-secondary,#94a3b8)]',
                                'dark:border-[var(--surface-border,rgba(255,255,255,0.1))]',
                                'dark:shadow-[0_1px_0_1px_rgba(0,0,0,0.4)]',
                            )}
                        >
                            {key}
                        </kbd>
                    </React.Fragment>
                ));
            }
            return (
                <kbd
                    className={cn(
                        'inline-flex h-5 min-w-[20px] items-center justify-center rounded px-1.5',
                        'text-[11px] font-medium font-mono leading-none',
                        'bg-[var(--surface-bg-subtle,#f8fafc)]',
                        'text-[var(--glass-text-secondary,#475569)]',
                        'border border-[var(--surface-border,#e2e8f0)]',
                        'shadow-[0_1px_0_1px_var(--surface-border,#e2e8f0)]',
                        'dark:bg-[var(--surface-bg-hover,rgba(255,255,255,0.08))]',
                        'dark:text-[var(--glass-text-secondary,#94a3b8)]',
                        'dark:border-[var(--surface-border,rgba(255,255,255,0.1))]',
                        'dark:shadow-[0_1px_0_1px_rgba(0,0,0,0.4)]',
                    )}
                >
                    {children}
                </kbd>
            );
        };

        return (
            <span
                ref={ref}
                className={cn('inline-flex items-center gap-0.5', className)}
                {...props}
            >
                {renderKeys()}
            </span>
        );
    }
);

GlassKbd.displayName = 'GlassKbd';

// packages/vue/src/components/glassmorphic/GlassKbd.vue
<script setup lang="ts">
/**
 * GlassKbd - Keyboard shortcut keycap display
 */
import { computed } from 'vue';
import { cn } from '@archui/core';

interface GlassKbdProps {
  keys: string | string[];
  separator?: string;
  size?: 'sm' | 'md' | 'lg';
  class?: string;
}

const props = withDefaults(defineProps<GlassKbdProps>(), {
  separator: '+',
  size: 'md',
});

const keyArray = computed(() =>
  Array.isArray(props.keys) ? props.keys : [props.keys]
);

const sizeClasses = computed(() => {
  const map: Record<string, string> = {
    sm: 'min-w-[20px] h-5 px-1 text-[10px]',
    md: 'min-w-[24px] h-6 px-1.5 text-[11px]',
    lg: 'min-w-[28px] h-7 px-2 text-xs',
  };
  return map[props.size] || map.md;
});
</script>

<template>
  <span :class="cn('inline-flex items-center gap-1', $props.class)">
    <template v-for="(key, idx) in keyArray" :key="idx">
      <span
        v-if="idx > 0"
        class="text-[var(--glass-text-secondary,#475569)] dark:text-[var(--glass-text-secondary,#94a3b8)] text-[10px]"
      >
        {{ separator }}
      </span>
      <kbd
        :class="cn(
          'inline-flex items-center justify-center rounded-md font-mono font-medium',
          'bg-[var(--surface-bg-hover,#f1f5f9)] dark:bg-[rgba(255,255,255,0.08)]',
          'text-[var(--glass-text-secondary,#475569)] dark:text-[var(--glass-text-secondary,#94a3b8)]',
          'border border-[var(--surface-border,#e2e8f0)] dark:border-[rgba(255,255,255,0.12)]',
          'shadow-[0_1px_0_1px_var(--surface-border,#cbd5e1)] dark:shadow-[0_1px_0_1px_rgba(0,0,0,0.3)]',
          sizeClasses,
        )"
      >
        {{ key }}
      </kbd>
    </template>
  </span>
</template>
