// packages/vue/src/components/dashboard/motion-driven/MotionStatCard.vue
<script setup lang="ts">
/**
 * MotionStatCard – Motion-Driven (Vue 3)
 * Card entrance animation on mount + hover scale microinteraction.
 * Uses CSS animations triggered via onMounted.
 */

import { ref, onMounted, computed } from 'vue'
import type { StatCardData } from '../shared/types'

const props = withDefaults(defineProps<{
  data: StatCardData
  index?: number
}>(), {
  index: 0
})

const isVisible = ref(false)
const isHovered = ref(false)

onMounted(() => {
  // Staggered entrance delay
  setTimeout(() => {
    isVisible.value = true
  }, props.index * 80)
})

const cardStyle = computed(() => ({
  transitionDelay: isVisible.value ? '0ms' : `${props.index * 80}ms`,
  transform: isHovered.value ? 'scale(1.02)' : 'scale(1)',
  boxShadow: isHovered.value ? 'var(--dash-shadow-lg)' : 'var(--dash-shadow-sm)',
}))
</script>

<template>
  <article
    :class="[$style.statCard, isVisible && $style.visible]"
    :style="cardStyle"
    :aria-label="`${data.label}: ${data.value}`"
    @mouseenter="isHovered = true"
    @mouseleave="isHovered = false"
  >
    <span :class="$style.statCardIcon" aria-hidden="true">{{ data.icon }}</span>
    <p :class="$style.statCardLabel">{{ data.label }}</p>
    <p :class="$style.statCardValue">{{ data.value }}</p>
    <span
      :class="[
        $style.statCardChange,
        data.trend === 'up' ? $style.trendUp :
        data.trend === 'down' ? $style.trendDown :
        $style.trendNeutral
      ]"
    >
      {{ data.trend === 'up' ? '↑' : data.trend === 'down' ? '↓' : '→' }}
      {{ data.change }}
    </span>
  </article>
</template>

<style module>
.statCard {
  padding: 24px;
  border-radius: 16px;
  background: var(--dash-surface);
  border: 1px solid var(--dash-border-subtle);
  cursor: default;
  will-change: transform, box-shadow;
  transition: transform 200ms cubic-bezier(0.4, 0, 0.2, 1),
              box-shadow 200ms cubic-bezier(0.4, 0, 0.2, 1),
              border-color var(--dash-transition-fast),
              opacity 400ms cubic-bezier(0.25, 0.46, 0.45, 0.94),
              translate 400ms cubic-bezier(0.25, 0.46, 0.45, 0.94);
  opacity: 0;
  translate: 0 24px;
}

.statCard:hover {
  border-color: var(--dash-border);
}

.statCard:active {
  transform: scale(0.98) !important;
}

.visible {
  opacity: 1;
  translate: 0 0;
}

.statCardIcon {
  font-size: 20px;
  margin-bottom: 16px;
  display: block;
}

.statCardLabel {
  font-size: 13px;
  font-weight: 500;
  color: var(--dash-text-muted);
  text-transform: uppercase;
  letter-spacing: 0.04em;
  margin: 0 0 8px;
}

.statCardValue {
  font-size: 30px;
  font-weight: 600;
  letter-spacing: -0.02em;
  color: var(--dash-text);
  margin: 0 0 8px;
  font-variant-numeric: tabular-nums;
}

.statCardChange {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  font-size: 13px;
  font-weight: 500;
  padding: 2px 8px;
  border-radius: 6px;
}

.trendUp {
  color: var(--dash-success);
  background: var(--dash-success-soft);
}

.trendDown {
  color: var(--dash-error);
  background: var(--dash-error-soft);
}

.trendNeutral {
  color: var(--dash-text-muted);
  background: var(--dash-border-subtle);
}
</style>

// packages/react/src/components/dashboard/motion-driven/MotionStatCard.tsx
'use client';

/**
 * MotionStatCard – Motion-Driven
 * Card entrance animation on load.
 * Hover scale + subtle elevation shift.
 */

import * as React from 'react';
import { motion } from 'motion/react';
import type { StatCardData } from '../shared/types';
import styles from './motion-driven.module.css';

interface MotionStatCardProps {
    data: StatCardData;
    /** Index for staggered entrance */
    index?: number;
}

export function MotionStatCard({ data, index = 0 }: MotionStatCardProps) {
    const trendClass =
        data.trend === 'up'
            ? styles.trendUp
            : data.trend === 'down'
                ? styles.trendDown
                : styles.trendNeutral;

    const trendArrow =
        data.trend === 'up' ? '↑' : data.trend === 'down' ? '↓' : '→';

    return (
        <motion.article
            className={styles.statCard}
            aria-label={`${data.label}: ${data.value}`}
            // Entrance animation
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{
                duration: 0.4,
                delay: index * 0.08,
                ease: [0.25, 0.46, 0.45, 0.94],
            }}
            // Hover microinteraction
            whileHover={{
                scale: 1.02,
                boxShadow: 'var(--dash-shadow-lg)',
                transition: { duration: 0.2, ease: [0.4, 0, 0.2, 1] },
            }}
            whileTap={{ scale: 0.98 }}
        >
            <span className={styles.statCardIcon} aria-hidden="true">
                {data.icon}
            </span>
            <p className={styles.statCardLabel}>{data.label}</p>
            <p className={styles.statCardValue}>{data.value}</p>
            <span className={`${styles.statCardChange} ${trendClass}`}>
                {trendArrow} {data.change}
            </span>
        </motion.article>
    );
}
